### ISSUE TITLE
Add monitoring solution

### ISSUE THREAD

**Issue by guiyomh** [webdevops/Dockerfile#109]
- [ ] Container filebeat (ex logstash-forwarder)
- [ ] Container logstash
- [ ] Container graphana( or Kibana ?)
- [ ] Container ElasticSearch ? Or InfluxDb ?

**Comment by hhoechtl** [comment]
As all logs are passed to stdout and stderr from the images, they're available to the docker daemon.

The docker daemon can then be configured with a logging driver to pass the logs to whatever you want: https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers

Therefore this issue will be closed. Maybe we could provide some additional repository containing an ELK, graylog or something else with predefined parsers (as all logs are mixed together in the docker output) and some dashboards, but that would be a different issue.
