### ISSUE TITLE
Add Blackfire env vars

### ISSUE THREAD

**Issue by choonge** [webdevops/Dockerfile#113]
Blackfire needs an id and token to be written to its .ini file. It looks quite similar to #90 . Would be nice to implement both of these in the same manner. Any idea how #90 will be built? Read an env var and have an entrypoint.d script write it to the .ini?

**Comment by mblaschke** [comment]
`BLACKFIRE_TOKEN`?
`BLACKFIRE_ID`?

**Comment by choonge** [comment]
I would match the php.ini variable naming as closely as possible, so `BLACKFIRE_SERVER_ID` and `BLACKFIRE_TOKEN`. But, do you agree that having an entrypoint.d script set this, is the correct way? Or is there a better place to do this, in the big picture of the project?
