### ISSUE TITLE
Blackfire needs blackfire-agent to work

### ISSUE THREAD

**Issue by choonge** [webdevops/Dockerfile#116]
If a user chooses blackfire as PHP_DEBUGGER, the agent should get installed as well. That agent comes from the same blackfire.io repository. After installing the package, the server_id and server_token should be written to /etc/blackfire/agent.json, and the service should be started.

Reference: https://blackfire.io/docs/up-and-running/installation

**Comment by mblaschke** [comment]
Added to https://github.com/webdevops/Dockerfile/tree/feature/php-dev-env-vars

**Comment by choonge** [comment]
I love you. Thanks!
