### ISSUE TITLE
Setting CMD breaks running container

### ISSUE THREAD

**Issue by jengo** [webdevops/Dockerfile#120]
I have a script that needs to be executed during container launch.  This is because it needs the environment variables set from chef.  After that, I can run my script and after run supervisord.

However, as soon as I set CMD the container no longer functions and I get an error like:
/bin/sh: 1: test.sh: not found

I have tried changing the ENTRYPOINT in a dozen different ways and can't seem to find the right combo.

Just for kicks, I tried using python:3.5-onbuild as my base image and what I was doing worked fine.  The difference between this is that the python container does not set an ENTRYPOINT.

What can I do ?

**Comment by mblaschke** [comment]
You can `ADD` or `COPY` your script into `/opt/docker/provision/entrypoint.d/` (make sure it has .sh ending). It will automatically be executed before supervisor start :)

See http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/base.html#provisioning

Does this help?

**Comment by guiyomh** [comment]
We can  close this issue ?

**Comment by Mugane** [comment]
> You can `ADD` or `COPY` your script into `/opt/docker/provision/entrypoint.d/` (make sure it has .sh ending). It will automatically be executed before supervisor start :)
> 
> See http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/base.html#provisioning
> 
> Does this help?

How does this help when you use `docker run` ? How do you pass a command to the run statement without causing the entrypoint to be overridden and the container to exit immediately?
