### ISSUE TITLE
PHP7 version, not pre-loaded with pear, cannot use pecl install expansion

### ISSUE THREAD

**Issue by ndj888** [webdevops/Dockerfile#129]
Thank you for your open source.Docker image tag debian-8-php7 debian-9 ubuntu-16.04 not used pecl.
I'm looking forward to update, in order to solve this problem.

The error message:
Step 5 : RUN pear install redis-3.0.0
 ---> Running in ec1dfa851941
/bin/sh: 1: pear: not found
The command '/bin/sh -c pear install redis-3.0.0' returned a non-zero code: 127

**Comment by hhoechtl** [comment]
Redis is already included and testing this with a current images does work
