### ISSUE TITLE
Nginx duplicate location "/"

### ISSUE THREAD

**Issue by hhoechtl** [webdevops/Dockerfile#134]
The image `webdevops/php-nginx-dev:ubuntu-16.04` is not working, due to:

```
app_1            | nginx: [emerg] duplicate location "/" in /opt/docker/etc/nginx/vhost.common.d/10-location-root.conf:1
```

Because that file duplicates the location which is already present in `/opt/docker/etc/nginx/vhost.conf`

**Comment by guiyomh** [comment]
hi @hhoechtl ,
what is the version of your container ``webdevops/php-nginx-dev:ubuntu-16.04`` ?

Could you run 

```
docker inspect -f "{{ .Config.Labels}}" 
```

**Comment by guiyomh** [comment]
I don't see a duplicate location in the last image.

```
vagrant@DEV-VM ~/projects/infogene/Dockerfile % docker run -d --name ng webdevops/php-nginx-dev:ubuntu-16.04
7f9224afdf627853a49ffc4487894a7f5558a284a23c3f1ce282477d273df41d
vagrant@DEV-VM ~/projects/infogene/Dockerfile % docker exec -ti ng bash
root@7f9224afdf62:/# cat /opt/docker/etc/nginx/vhost.conf
server {
    listen   80 default_server;
    listen 8000 default_server;

    server_name  _ *.vm docker;

    access_log   /dev/stdout;
    error_log    /dev/stdout info;

    root "/app";
    index index.php;

    client_max_body_size 50m;

    include /opt/docker/etc/nginx/vhost.common.d/*.conf;
}

##############
# SSL
##############

server {
    listen  443 default_server;
    listen 8443 default_server;

    server_name  _ *.vm docker;

    access_log   /dev/stdout;
    error_log    /dev/stdout info;

    root "/app";
    index index.php;

    client_max_body_size 50m;

    include /opt/docker/etc/nginx/vhost.common.d/*.conf;
    include /opt/docker/etc/nginx/vhost.ssl.conf;
}
```

And the configuration of nginx seem be ok !
```
vagrant@DEV-VM ~/projects/infogene/Dockerfile % docker exec -ti ng nginx -t                                                                                                                
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by hhoechtl** [comment]
map[io.webdevops.layout:8 io.webdevops.version:0.56.1 vendor:WebDevOps.io]

**Comment by mblaschke** [comment]
Any clue where it happens?

**Comment by mblaschke** [comment]
Any further informations?

**Comment by j2hcom** [comment]
The issue is a change in vhost configuration from webdevops/php-nginx:ubuntu-16.04-php7 to latest webdevops/php-nginx:ubuntu-16.04.

The configuration within the image itself works fine and has no configuration conflicts. But while generating a custom vhost.conf like used with the https://github.com/webdevops/php-docker-boilerplate we will have a "location /" within vhost.conf and another in /opt/docker/etc/nginx/vhost.common.d/10-location-root.conf. And here something changed within about one month ago im comparrison to webdevops/php-nginx:ubuntu-16.04-php7, where the same vhost configuration worked fine.

**Comment by guiyomh** [comment]
@mblaschke may be we should transfer this issue to php-docker-boilerplate project ?
