### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by hhoechtl** [webdevops/Dockerfile#136]
The symlink created by ansible has mod 777 and is therefore not being executed:
```
Sep 26 06:50:01 2440744b217b cron[330]: (*system*docker-boilerplate) INSECURE MO
DE (group/other writable) (/etc/cron.d/docker-boilerplate)
```

Im not that familiar with ansible, but I think the `mode` must be added to the "Create link for crontab" task.

Tested with Ubuntu-16.04. No idea if other images are affected.

**Comment by mblaschke** [comment]
It's bug inside the php/TYPO3 docker boilerplate. Can you retest with `develop` branch?

**Comment by hhoechtl** [comment]
Yes, tomorrow.

**Comment by hhoechtl** [comment]
Yes it works
