### ISSUE TITLE
Issue with apk add on alpine-3-php7

### ISSUE THREAD

**Issue by Dudemullet** [webdevops/Dockerfile#149]
For like a week or so, I'm not able to do 

`
RUN apk add --no-cache php7-xdebug
`

Every other package works, any idea why all of a sudden this could have broken ?

**Comment by Dudemullet** [comment]
Ok, I think this has to do with differences between `alpine-3.3` and `alpine-3.4`. Is there a way to pick a more specific version ?

**Comment by mblaschke** [comment]
There are currently build issues with alpine-3-php7.. Will try to fix it in the next days.

**Comment by Dudemullet** [comment]
In the meantime, if you're experiencing this issue, adding the `edge/community` repo to my repositories (sources) file fixed the issue. _results may vary_

> Add this to your docker file before _apk add_

```
# Add community repo to end of sources list
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
```

**Comment by mblaschke** [comment]
We have some problems for the current alpine image to get php7 running.. we're still trying to get it running

**Comment by Dudemullet** [comment]
@mblaschke Are there any current issues or PR's tracking those problems ? Could help point me in the right direction and I'll try and help.

**Comment by mblaschke** [comment]
Should be fixed since some weeks :)

**Comment by Dudemullet** [comment]
Thanks @mblaschke
