### ISSUE TITLE
command missing

### ISSUE THREAD

**Issue by thonatos** [webdevops/Dockerfile#152]
it seems that the image missing the command: 'mkdir -p -- /etc/dnsmasq.d/',

- image: webdevops/php-nginx:alpine-3
- file: /opt/docker/bin/service.d/dnsmasq.d/10-init.sh

the 'base-app' do have the line: 

```
# webdevops/base-app:alpine-3
# https://github.com/webdevops/Dockerfile/blob/develop/docker/base-app/alpine-3/conf/bin/service.d/dnsmasq.d/10-init.sh

# Create dnsmasq.d directory if not exists
mkdir -p -- /etc/dnsmasq.d/
```

so, i think you may rebuild the base-app to make the php-nginx:alpine-3 work

**Comment by mblaschke** [comment]
Already fixed in develop :)

**Comment by mblaschke** [comment]
Fixed in master, new builds tomorrow should be fixed :)
