### ISSUE TITLE
/dev/null permissions

### ISSUE THREAD

**Issue by cdaguerre** [webdevops/Dockerfile#153]
I use `webdevops/php-nginx:ubuntu-16.04` and recently updated to the current version.
Since then, I get a bunch of permission errors when running selenium tests because xvfb-run gets permission denied on `/dev/null`. Any idea what the problem could be?

**Comment by mblaschke** [comment]
Oh.. we will look at it and include it into our tests.. thanks for reporting :)

**Comment by mblaschke** [comment]
Can you give us the output of `docker run -ti --rm webdevops/php-nginx:ubuntu-16.04 'ls -l /dev/'`?

If you're extending the image please attach the `ls -l /dev/` output from the image.

Here we have:

```
total 0
crw------- 1 root root 136,   0 Dec 19 20:24 console
lrwxrwxrwx 1 root root       11 Dec 19 20:24 core -> /proc/kcore
lrwxrwxrwx 1 root root       13 Dec 19 20:24 fd -> /proc/self/fd
crw-rw-rw- 1 root root   1,   7 Dec 19 20:24 full
crw-rw-rw- 1 root root  10, 229 Dec 19 20:24 fuse
drwxrwxrwt 2 root root       40 Dec 19 20:24 mqueue
crw-rw-rw- 1 root root   1,   3 Dec 19 20:24 null
lrwxrwxrwx 1 root root        8 Dec 19 20:24 ptmx -> pts/ptmx
drwxr-xr-x 2 root root        0 Dec 19 20:24 pts
crw-rw-rw- 1 root root   1,   8 Dec 19 20:24 random
drwxrwxrwt 2 root root       40 Dec 19 20:24 shm
lrwxrwxrwx 1 root root       15 Dec 19 20:24 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root       15 Dec 19 20:24 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root       15 Dec 19 20:24 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root   5,   0 Dec 19 20:24 tty
crw-rw-rw- 1 root root   1,   9 Dec 19 20:24 urandom
crw-rw-rw- 1 root root   1,   5 Dec 19 20:24 zero
```

**Comment by cdaguerre** [comment]
Thanks for your help. I rebuilt my Dockerfile from scratch and the issue disappeared.

**Comment by mblaschke** [comment]
I've repopened it because we should add a testcase for this bug :)

Will close it when test is added to repository

**Comment by sergeyklay** [comment]
```
docker run -ti --rm webdevops/php-nginx:ubuntu-16.04 'ls -l /dev/'
/opt/docker/bin/entrypoint.d/default.sh: line 3: /ls -l /dev/: No such file or directory
```

**Comment by mblaschke** [comment]
please use `docker run -ti --rm webdevops/php-nginx:ubuntu-16.04 ls -l /dev/` (i've replaced the "improved command execution" change from docker images because it was buggy)
