### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by cdaguerre** [webdevops/Dockerfile#157]
Hi, any ETA on PHP7.1 support? Thanks for the great job by the way.

**Comment by mblaschke** [comment]
We're currently planing to adapt the official php images and add nginx/apache and all the stuff to it :)

**Comment by toancong** [comment]
Great! Hope to see this soon. Thanks!

**Comment by thebennos** [comment]
+1

**Comment by mblaschke** [comment]
Comming with `feature/php-official`

**Comment by mblaschke** [comment]
Will be pushed this week to docker hub

**Comment by mblaschke** [comment]
official images are now pushed to docker hub 🎉
