### ISSUE TITLE
[Need] Enable ErrorLog for Apache

### ISSUE THREAD

**Issue by cosmospham** [webdevops/Dockerfile#159]
How to enable ErrorLog for Apache? I want to view Access Log and Error Log in somewhere like `/var/log/apache2/error.log`.

I checked and saw that `ErrorLog  /proc/self/fd/2` in `/laradock/apache2/conf/etc/httpd/conf.d/10-log.conf`. Tried to change to another value but it is not valid.

**Comment by mblaschke** [comment]
it should be posted to `docker logs`, isn't it available there?

**Comment by cosmospham** [comment]
I found the solution:

- Add to `php-fpm/Dockerfile-56`:

 ```
 RUN mkdir /var/log/php-fpm
 ```

- Add to `php-fpm/laravel.ini`:

 ```
 log_errors=On
 error_log = /var/log/php-fpm/error.log
 error_reporting=1
 ```

The problem occurs when there is no directory exists (`/var/log/php-fpm`) for the logging file.

**Comment by mblaschke** [comment]
These logs shout be directed to syslog or /docker.stdout. There should be no single logfile in the container because you're losing them if the container is recreated.

**Comment by mblaschke** [comment]
Just notices that these docker images are not based on our images so please report it to laradock :)
