### ISSUE TITLE
Multiple applications, local mappings

### ISSUE THREAD

**Issue by grantpalin** [webdevops/Dockerfile#164]
Just got an instance of this container running, and can access the localhost:81.

Something I haven't got clear yet is the intended scope of this container - is it intended to run a single app per instance, or can it run multiple apps (virtual hosts)? I suppose it shouldn't be a big issue to run multiple containers, given the lightweight nature, but having to spin up one container per project seems daunting.

Also, the documentation doesn't seem to say anything about how to get code in place for the container to run. Is there supposed to be a mapping created between the container's `/app` folder and the host machine?

Would https://github.com/webdevops/php-docker-boilerplate make more sense to be used on a per-project basis?

**Comment by mblaschke** [comment]
You could do both, either one app per container or multiple apps per container.

If you want multiple apps per container you have to configure you're vhost manually by creating/overwriting files inside the `vhost.d` directory.

nginx: `/opt/docker/etc/nginx/vhost.conf`
apache: `/opt/docker/etc/httpd/vhost.conf`

We don't want to limit to one app per container but it's possible by manually upload a custom configuration into the image/container :)

Normally you have one container per app but the world is more complex than that... :)

**Comment by grantpalin** [comment]
After some more reading I find myself aligning with the container-per-app perspective. It makes sense to keep applications and their dependencies separate for modularity and popularity.

I elected to make use of the boilerplate linked above, and eventually figured out how to do the mapping to a local folder. So I've gotten started!
