### ISSUE TITLE
Certbot dependency

### ISSUE THREAD

**Issue by Applemann** [webdevops/Dockerfile#168]
When I run:
`docker run -it webdevops/certbot:latest certbot certonly --manual --preferred-challenges dns --email martin.jablecnik@email.cz -d teamzeus.com`

I get output:  `Self verification requires optional dependency `dnspython` to be installed.      `                                             

Can you please install the dnspython dependency?

**Comment by mblaschke** [comment]
Should be fixed with next build this night (CEST)
Thanks for reporting :)
