### ISSUE TITLE
php-mongodb for php-nginx:latest

### ISSUE THREAD

**Issue by kamilko** [webdevops/Dockerfile#170]
Please add `php-mongodb` module to default configuration.

Thanks

**Comment by leonardodelfino** [comment]
+1

**Comment by aahmadts** [comment]
you can install mongodb using this command as taken from [mongodb official website](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/):
*consider changing first two lines for other os versions.


`RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6 &&\
    echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list && \
    apt-get update &&\
    apt-get -y install mongodb-org &&\
    sleep 5 &&\
    service mongod start`


and for adding mongod-ext to php modules you can install it using `pelc` like this:
`RUN  pecl install oauth-1.2.3 mongodb-1.2.0`

then added it to php extensionsusing this:
`RUN echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/docker-php-ext-mongod.ini`
