### ISSUE TITLE
Boilerplate FROM php-apache-dev:5.6 build fails without cron enabled

### ISSUE THREAD

**Issue by avc** [webdevops/Dockerfile#171]
In trying to build an instance of webdevops biolerplate Dockerfile.development based on php-apache-dev:5.6, this error is reported:
> ln: failed to create symbolic link ‘/etc/cron.d/docker-boilerplate’: No such file or directory

php-apache-dev:ubuntu-15.04 builds successfully because cron is enabled in an ancestor Dockerfile php:ubuntu-15.04. In contrast, its peer php:5.6 (ancestor of php-apache-dev:5.6) does not enable cron.

**Comment by mblaschke** [comment]
Fixed with d709860eed318237667ec4f32416ab24ddba2178
Will be included in images build this night (CEST)

Our plan is to replace cron anyway with a better solution in the next weeks.
Thanks for the issue :)
