### ISSUE TITLE
Error while using webdevops/liquibase:mysql

### ISSUE THREAD

**Issue by porebskk** [webdevops/Dockerfile#173]
Hello,

first I wanted to say thanks for the great docker images.  
Since this week the liquibase:mysql image isn't working for me. I assume this is related to the "Switch to shell based provisioning" task. The error I receive when starting the container is:
```
container_linux.go:247: starting container process caused "exec: \"/entrypoint\": stat /entrypoint: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/entrypoint\": stat /entrypoint: no such file or directory".
time="2017-05-18T15:23:06+02:00" level=error msg="error getting events from daemon: net/http: request canceled" 
```

I'm using Docker on Windows 10 via Hyper-V

**Comment by mblaschke** [comment]
Fixed and pushed to docker hub with 5e14631a248d64c28a021d6eebf049b664d0dd97

Thanks for reporting
