### ISSUE TITLE
Error: Could not select mailbox in webdevops/mail-sandbox

### ISSUE THREAD

**Issue by wase90168** [webdevops/Dockerfile#175]
Everytime I run the docker image webdevops/mail-sandbox with default configuration and try to access it via a webbrowser I get the message that the mailbox isn't selectable (Displayed by roundcube and in the Container-Logs):

`[SYSLOG] dovecot: imap(dev): Error: Opening INBOX failed: Mailbox isn't selectable`

The whole throw out is:

[errorlog.txt](https://github.com/webdevops/Dockerfile/files/1021250/errorlog.txt)

**Comment by mblaschke** [comment]
Thanks for reporting :)
Fixed and pushed.
