### ISSUE TITLE
How to properly configure / enable xdebug

### ISSUE THREAD

**Issue by valorize** [webdevops/Dockerfile#176]
Hi I do not get xdebug to work.
I added a php.ini with `volumes:\n - ./php.ini:/opt/docker/etc/php/php.ini` with the contents:
```
xdebug.remote_connect_back=0
xdebug.remote_autostart=1
xdebug.remote_host=172.19.0.1
xdebug.remote_port=9021
xdebug.remote_log=/var/log/xdebug.log
```
It is properly listed in `php -i | grep remote`.

My PhpStorm is configured to listen on 9021 and `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker_php_1` gave `172.19.0.3` so `172.19.0.1` should be my host. But the xdebug log gives:
```
Log opened at 2017-05-25 12:26:06
I: Connecting to configured address/port: 172.19.0.1:9021.
E: Could not connect to client. :-(
Log closed at 2017-05-25 12:26:06
```

**Comment by mblaschke** [comment]
Your docker container is running inside a linux VM (docker machine) which is running on your host?

So `172.19.0.1` is your linux VM where you're docker container is running.

Why not try `xdebug.remote_connect_back=1`? this should already be default inside our docker images :)

**Comment by mblaschke** [comment]
BTW: which docker solution are you using on what OS?

**Comment by valorize** [comment]
I'm running the docker vm (Version 17.03.1-ce-mac12 (17661)) provided for mac osx.
Therefore I cannot use connect_back as far as I know.

For now I'm using a orchestration of these: 
```
  php:
    image: webdevops/php-dev
    environment:
      - XDEBUG_REMOTE_AUTOSTART=1
      - XDEBUG_REMOTE_CONNECT_BACK=1
      ## IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
      ## docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker_php_1
      ##- XDEBUG_REMOTE_HOST=172.19.0.1
      - XDEBUG_REMOTE_PORT=9021
    volumes:
      - ..:/app
##      - ./php.ini:/opt/docker/etc/php/php.ini
    working_dir: /app
    links:
      - db:db_host

  apache:
    image: webdevops/apache-dev
    environment:
      - WEB_PHP_SOCKET=php:9000
    volumes:
      - ..:/app
    ports:
      - 80:80
      - 443:443
    links:
      - php

  db:
    image: mariadb
...
```

**Comment by mblaschke** [comment]
The 172 address should work on a linux host when docker is running directly in this host.
For osx you have to run an linux VM so this IP address is the address of your linux host.

Check your `ifconfig` if you find the network interface from your virtualisation and try this ip adress or your ip adress of your lan interface (but this can change from time to time).

**Comment by valorize** [comment]
I had to use `/Users/$USER/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp/host` to get the correct address. Maybe it's possible to set this address automatically?

**Comment by valorize** [comment]
so it looks now like:
```
    image: webdevops/php-dev
    environment:
      # IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
      # on linux: docker-compose exec php bash -c "route | awk '/^default/ { print \$2 }'"
      # on mac: cat /Users/$USER/Library/Containers/com.docker.docker/Data/database/com.docker.driver.amd64-linux/slirp/host
      - XDEBUG_REMOTE_HOST=192.168.65.1
      - XDEBUG_REMOTE_PORT=9000
      - XDEBUG_REMOTE_CONNECT_BACK=0
      - XDEBUG_REMOTE_AUTOSTART=1
```

**Comment by mblaschke** [comment]
hm.. connect back should also work, even with docker.

**Comment by mblaschke** [comment]
Maybe @hhoechtl, @PanadeEdu, @sergeyklay or @jousch can help.

**Comment by sergeyklay** [comment]
Actually I always used **`XDEBUG_REMOTE_CONNECT_BACK=0`**:
```ini
PHP_DEBUGGER=xdebug

XDEBUG_REMOTE_HOST=192.168.1.129 # my ip
XDEBUG_REMOTE_PORT=9000
XDEBUG_REMOTE_AUTOSTART=0
XDEBUG_REMOTE_CONNECT_BACK=0
```
