### ISSUE TITLE
Support for alpine:3.6

### ISSUE THREAD

**Issue by rivetmichael** [webdevops/Dockerfile#180]
Hello,
Do you plan to support Alpine 3.6 anytime ? I think it will be great in order to bring PHP 7.1 support.

Thank you

**Comment by mblaschke** [comment]
Will be build with next build run :)

**Comment by mblaschke** [comment]
We have problems with APCu on PHP5 with alpine 3.6
https://github.com/krakjoe/apcu/issues/250

**Comment by rivetmichael** [comment]
Thank you for Your  response

**Comment by mblaschke** [comment]
And found again the next issue... still working on this task :sweat:

Currently there is so many stuff missing for php.... :(

**Comment by hhoechtl** [comment]
Since we have all new alpine images, I'll close this issue.
