### ISSUE TITLE
Cannot copy file to /etc/apache2

### ISSUE THREAD

**Issue by tarikhagustia** [webdevops/Dockerfile#185]
Hallo i have Dockerfile with code like this
`FROM webdevops/php-apache:5.6

COPY ports.conf /etc/apache2/

LABEL Author="Tarikh Agustia<agustia.tarikh150@gmail.com>"

ENV PHP_DISPLAY_ERRORS On
`
but the ports.conf file not copied to apache etc dir, how to change apache port in php-apache docker images ?

thanks :)

**Comment by mblaschke** [comment]
What's the output and the exit code of your `docker build` process?
Can you make sure that the file doesn't exists if the new built image? Please check it with `docker exec -ti --rm <IMAGEID> ls -l /etc/apache2`

**Comment by tarikhagustia** [comment]
i have solve my prob by delete exist image and pull new image again,

if you add some env to change apache port, good to use this images, :))
