### ISSUE TITLE
WEB_PHP_TIMEOUT

### ISSUE THREAD

**Issue by mlalbuquerque** [webdevops/Dockerfile#188]
You included a new environment variable (WEB_PHP_TIMEOUT) in the build, but you didn't mention it in the docs neither has a default value in the Dockerfile. That's triggering an error:

`AH00526: Syntax error on line 9 of /opt/docker/etc/httpd/conf.d/10-php.conf`

Exactly, the same spot that has the marker:

`ProxySet connectiontimeout=5 timeout=<PHP_TIMEOUT>.`

I think you could set a default value for WEB_PHP_TIMEOUT.

**Comment by mf-lit** [comment]
Yes, seeing same issue here. That PR looks good to me.

**Comment by Claymm** [comment]
+1

**Comment by hhoechtl** [comment]
Already fixed 8 months ago in https://github.com/webdevops/Dockerfile/commit/d336cdc5b706d07e2f474ed043757b7d39fb4b31
