### ISSUE TITLE
Is Ansible provisioning still supported from the base container

### ISSUE THREAD

**Issue by computerfr33k** [webdevops/Dockerfile#190]
I have a docker container that is dependent on extending from webdevops/base:alpine but my ansible playbooks no longer seem to be working like they used to. And looking through this repo it seems all ansible playbooks have been removed for the other containers you maintain and so I'm wondering if ansible support has been discontinued and is no longer functional.

Thanks

**Comment by hhoechtl** [comment]
Ansible is no longer supported.

**Comment by bittner** [comment]
Not completely sure what "Ansible is no longer supported" is meant to mean here. :confused: 

There is a [webdevops/ansible](https://hub.docker.com/r/webdevops/ansible/) image on Docker Hub. Irritatingly, the latest image build there is from 3 years ago, with `ubuntu-15.10` as the newest supported GNU/Linux distro image. Does that mean the image is deprecated and unmaintained? -- (A hint in the README would be nice.)

**Side note:** I'm interested in (adding)`ssh-agent` support to an image suitable for running Ansible. Because [adding support for deployments that use SSH](https://docs.gitlab.com/ce/ci/ssh_keys/#ssh-keys-when-using-the-docker-executor) is pretty annoying on GitLab CI.

**Comment by hhoechtl** [comment]
An early version of our images was built using ansible. As this caused a lot of additional maintenance and unflexibility, we switched to a standard script based provisioning approach. That has nothing to do with the `webdevops/ansible` image. This image is built with the supported tags (distro versions) and that was 4 hours ago.

Regarding your side note: Deployment with SSH in Gitlab is very easy, just copy paste the lines from your link. We use it in over 100 projects that way.

**Comment by bittner** [comment]
> Deployment with SSH in Gitlab is very easy, just copy paste the lines from your link. We use it in over 100 projects that way.

Sure, but copy+paste is not my preferred style. It's not about "how to make it work", it's about elegance and maintainability. At least the `ssh-agent` package could be preinstalled on an Image that hosts Ansible. In the end, it's probable that this image is use for running Ansible against a host that allows connecting with SSH, isn't it? I think it would make sense.

**Comment by hhoechtl** [comment]
Well, using the recommended way suggested by the creator of Gitlab => Gitlab ...

But pre-installing the openssh-client package to the ansible image makes sense. Most other images already contain it.

**Comment by bittner** [comment]
> Well, using the recommended way suggested by the creator of Gitlab => Gitlab ...

They are still humans only. And it makes sense not to include the setup on a generic ci-runner image. But an image the works with SSH anyway ...

> But pre-installing the openssh-client package to the ansible image makes sense. Most other images already contain it.

Can you suggest how to do that with your Dockerfile code? From the graphic I'm not sure you want to "pollute" the Ansible image with something related to SSH.

**Comment by hhoechtl** [comment]
It needs to be added to the ansible templates, as this image only builds on top of bootstrap. The openssh-client is added during base-app in the other images

**Comment by bittner** [comment]
Wow, this looks like a lot of magic! Can you tell me exactly which file(s) I have to touch to add the package? Even in `base-app` "everything" seems to be auto-generated.  :confused:

**Comment by hhoechtl** [comment]
Everything is auto generated out of the jinja2 templates. In this case, edit `templates/Dockerfile/images/ansible.jinja2` and run `make provision`
