### ISSUE TITLE
Multiple webroot support

### ISSUE THREAD

**Issue by timkelty** [webdevops/Dockerfile#195]
I have an app that has 2 separate document roots, eg:

- app/sites/siteA/index.php
- app/sites/siteB/index.php

Is there a way I can run both on different ports?

**Comment by josefglatz** [comment]
Why not using additional container?

**Comment by timkelty** [comment]
@josefglatz sure, I guess in this case I wanted them both running in the same php-nginx container

**Comment by hhoechtl** [comment]
The use case is very rare.

You could build a custom image based on the webdevops images and overwrite the file `/opt/docker/etc/nginx/vhost.conf` to listen on different ports with different docroots.

Your `vhost.conf`:
```
server {
    listen 80 default_server;
    server_name  _ *.vm docker;
    root "/app/sites/siteA";
    index index.php;
    include /opt/docker/etc/nginx/vhost.common.d/*.conf;
}
server {
    listen 81 default_server;
    server_name  _ *.vm docker;
    root "/app/sites/siteB";
    index index.php;
    include /opt/docker/etc/nginx/vhost.common.d/*.conf;
}
```

A `Dockerfile` could look like:

```
FROM webdevops/php-nginx-dev:7.2
COPY vhost.conf /opt/docker/etc/nginx/
```
