### ISSUE TITLE
Patch command is missing on webdevops/php-apache-dev

### ISSUE THREAD

**Issue by Kianda** [webdevops/Dockerfile#196]
http://manpages.ubuntu.com/manpages/xenial/man1/patch.1.html

Let's say our project have some *.patch files to apply via composer.
During a "composer install", on a project, composer will fallback to patch command if the git-apply of the *.patch file will return an error.
I think it's useful to add this command on the image webdevops/php-apache-dev

What do you think?
Thanks!

**Comment by Kianda** [comment]
Btw this is solved adding:
apt-get update && apt-get install patch

**Comment by josefglatz** [comment]
@Kianda Could you create a PR for that?

**Comment by josefglatz** [comment]
@Kianda And what about doing the composer stuff outside of the container? I only run composer commands in container, where database connections are necessary to another docker container.

**Comment by Kianda** [comment]
@josefglatz  sorry I'm late! :D

1. Can't do a PR, what I have is a start.sh script that run the container (docker-compose  up -d) and then do:
`docker exec -it --user root container-name /bin/bash -c "apt-get -qq update && apt-get -qq install -y patch"`
This allow me to use composer install (with patch) from inside the container.

2. My objective was to have only git as a requirement on the host machine but running composer outside the container is also a solution!
