### ISSUE TITLE
PHP 7.2 tags

### ISSUE THREAD

**Issue by addshore** [webdevops/Dockerfile#211]
PHP 7.2 was released on 30 Nov 2017 and it would be great to have this supported by the webdevops images soon!

**Comment by josefglatz** [comment]
xdebug isn't released for PHP 7.2.

See
- https://bugs.xdebug.org/roadmap_page.php?version_id=51
- https://xdebug.org/#2017_12_02

**Comment by josefglatz** [comment]
Update: xdebug RC2 version is available – but not released yet. Still waiting...

**Comment by janbuecker** [comment]
Update: xdebug 2.6 is finally released

**Comment by neusta-srademacher** [comment]
hey, is there any news here?

**Comment by leokun** [comment]
clone and build it yourself. This is what I  have done at our workplace.

**Comment by neusta-srademacher** [comment]
sure, i can do that but i don't think it's the goal of this project.

**Comment by agarzon** [comment]
I'm missing something? 7.2 tag just doesn't work, but it's documented http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html
```
docker pull webdevops/php-nginx-dev:7.2
Error response from daemon: manifest for webdevops/php-nginx-dev:7.2 not found

```

**Comment by bluefrg** [comment]
I know this isn't the best solution but I need to use this tag now so I created a **temporary** unofficial image. 

Just switch up the account until this issue is resolved:
`FROM bluefrg/php-nginx-dev:7.2`

https://hub.docker.com/r/bluefrg/php-nginx-dev/

**Comment by helmuthva** [comment]
@mblaschke - will the 7.2 tag be supported in the near future?

**Comment by hhoechtl** [comment]
We now have:
```
webdevops/php-nginx-dev:7.2
webdevops/php-nginx:7.2
webdevops/php-apache-dev:7.2
webdevops/php-apache:7.2
webdevops/php-dev:7.2
webdevops/php:7.2
```
working and available on docker hub.
