### ISSUE TITLE
Ubuntu 15.04: get an errror "W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/vivid/main/source/Sources  404  Not Found [IP: 91.189.88.162 80]"

### ISSUE THREAD

**Issue by lchhieu** [webdevops/Dockerfile#212]
I use Ubuntu 15.04, but i get an error   "W: Failed to fetch 
```
Ign http://archive.ubuntu.com vivid InRelease
Ign http://archive.ubuntu.com vivid-updates InRelease
Ign http://archive.ubuntu.com vivid-security InRelease
Ign http://archive.ubuntu.com vivid Release.gpg
Ign http://archive.ubuntu.com vivid-updates Release.gpg
Ign http://archive.ubuntu.com vivid-security Release.gpg
Ign http://archive.ubuntu.com vivid Release
Ign http://archive.ubuntu.com vivid-updates Release
Ign http://archive.ubuntu.com vivid-security Release
Ign http://archive.ubuntu.com vivid/main amd64 Packages/DiffIndex
Ign http://archive.ubuntu.com vivid/restricted amd64 Packages/DiffIndex
Err http://archive.ubuntu.com vivid/main Sources
http://archive.ubuntu.com/ubuntu/dists/vivid/main/source/Sources  404  Not Found [IP: 91.189.88.162 80]"
```

**Comment by awephuck** [comment]
I'm having the same issue on a VPS,  is there a fix for this?

**Comment by mblaschke** [comment]
Ubuntu 15.04 is EOL from Canonical.

**Comment by awephuck** [comment]
Thought that might be the case... when I try to do any update command or sudo do-release-upgrade I get the same error.  Do you know what I should change my source.list file to so I can perform the upgrade?  I don't have physical access to the box.   Thanks

**Comment by mblaschke** [comment]
Why don't you use the 16.04 image? don't run `apt-get dist-upgrade` or `do-release-upgrade` inside docker :)

**Comment by panigrc** [comment]
A solution is to write the following command in your Dockerfile.development after the `COPY` commands, in order to change the sources.list repositories to point to the old releases.
```
RUN sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
```

**Comment by janwerner** [comment]
Hi @mblaschke 
What do you suggest if older PHP versions are needed for testing? If I understand correctly, you chose to use different Ubuntu versions so stock PHP packages could be used vs. using 3rd-party repos etc.

Could you update the sources.list as suggested by @panigrc for those who want to stay with these versions, even if they're EOL?

**Comment by hhoechtl** [comment]
I've created a somewhat larger PR https://github.com/webdevops/Dockerfile/pull/240 which contains the fix for `old-releases` as well as the newest ubuntu versions.

**Comment by hhoechtl** [comment]
Since no more reviews are coming, I merged the PR and we will have new Ubuntu builds tonight.
