### ISSUE TITLE
Keep the suid bit on gosu?

### ISSUE THREAD

**Issue by loadaverage** [webdevops/Dockerfile#213]
I need to run FPM with www-data user, just for compatibility with default Debian's user:group for Nginx and other services.

So, I can specify `user: www-data` with docker-compose or `--user=www-data` from Docker cli. For the first start everything is OK, but the problems begins after container's restart.

As suid bit was removed from gosu here:
https://github.com/webdevops/Dockerfile/blob/33057dd78422c57ed41e2b8786516d3318f300ca/docker/base/debian-8/conf/bin/entrypoint.sh#L18 
There is no way to gain root privileges now, and container fails to start:
`error: failed switching to "root": operation not permitted`

Also, I see that [docs](http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html) explicitly describing that user specifying is allowed:
>This image is using supervisor and runs the daemon under user application (UID 1000; GID 1000) as default. If the container is started under a different user the daemon will be run under the specified uid.

So, is there any way to get back suid bit in this image?

**Comment by PanadeEdu** [comment]
I mark this duplicate from #226 since it is the best bet so far.

**Comment by hhoechtl** [comment]
Should be resolved with https://github.com/webdevops/Dockerfile/pull/333
