### ISSUE TITLE
Change user UID and GID

### ISSUE THREAD

**Issue by juuuuuu** [webdevops/Dockerfile#217]
Hello,

Thank you for your work on this project.  
I have a small issue. Is there a way to change the `application` UID and GID?  
I tried to set the following env var `APPLICATION_UID` and `APPLICATION_GID` but that does not affect the current user `application`.  
I'm trying to do that because in some developers environment, the UID and GID === 1001, and not 1000, as user `application`.

How could I do that?

Thx

edit: 
![capture d ecran de 2018-02-08 09-54-49](https://user-images.githubusercontent.com/1769769/35963785-28eebca2-0cb6-11e8-8e8a-4f82ff43409c.png)

**Comment by tbal** [comment]
@juuuuuu: Did you found a solution you could share?

**Comment by BenjaminBeck** [comment]
@juuuuuu ping

**Comment by juuuuuu** [comment]
Yes. Sadly, I stopped using this Docker image :/

**Comment by kitzberger** [comment]
I'm current always using this snippet here at the very end of the Dockerfile.development:

```
# Fix application uid/gid
ENV APPLICATION_UID_OVERRIDE 1001
ENV APPLICATION_GID_OVERRIDE 1001
RUN echo "Change uid/gid of 'application' user ($APPLICATION_UID_OVERRIDE:$APPLICATION_GID_OVERRIDE)" && \
    usermod -u $APPLICATION_UID_OVERRIDE application && \
    groupmod -g $APPLICATION_GID_OVERRIDE application && \
    usermod -g $APPLICATION_GID_OVERRIDE application &&     \
    chown "$APPLICATION_USER":"$APPLICATION_GROUP" -R /app /home/application
```

A rather rough solution, but gets the job done ;-)
