### ISSUE TITLE
Sendmail does not Work with 7.1 and 7.2 Tag

### ISSUE THREAD

**Issue by neusta-srademacher** [webdevops/Dockerfile#220]
In an older Project I use ubuntu16.04 Tag with PHP 7.0. In this Version Sendmail works great with mailhog. In a new Project I need PHP 7.2 but unfortunately Sendmail does not work. Is the integration planned there or am i doing something wrong?

**Comment by hhoechtl** [comment]
I solved the issue for the `-dev` images based on the official PHP images.

Please note: if you want to use `sendmail` in non `-dev` images, you must have your own Dockerfile and add `RUN docker-service enable postfix` or otherwise sendmail will not be available.

**Comment by ad-on-is** [comment]
Is there a reason why this is only in the `-dev` images, and not in the `php` or `php-nginx` image?

**Comment by hhoechtl** [comment]
I'm not sure about this, but this would be a separate issue to enable postfix on non-dev images by default.

**Comment by ad-on-is** [comment]
Why? Neither the title nor the description did mention anything about `dev`. According to my understanding, the issue is supposed to be fixed on non`-dev` images too.

**Comment by hhoechtl** [comment]
They are fixed as well. But somebody sometime in the past made the decision not to enable postfix in the non `-dev` images based on php official. So this needs to be discussed separately.
If you enable postfix on non`-dev` now, it works. Before the path it didn't.

**Comment by ArulselvanJaya** [comment]
Above mentioned changes i did but mail not received. 
Error:
root@5caaa911d2b7:/# echo "Subject: sendmail test" | sendmail -v xyz@gmail.com
postdrop: warning: unable to look up public/pickup: No such file or directory
Mail Delivery Status Report will be mailed to <root>.

**Comment by hhoechtl** [comment]
@ArulselvanJaya 

```
FROM webdevops/php:7.3
RUN docker-service enable postfix
```

```
docker build -t sendmailtest .
docker run -d --name sendmailtest sendmailtest
docker exec -ti sendmailtest bash
root@ac2fc16a127a:/# echo "Subject: sendmail test" | sendmail -v test@gmail.com
Mail Delivery Status Report will be mailed to <root>.
```

Works as expected.

You must have a running container so `supervisord` is running and therefore postfix. It's not possible to test this with `docker run`

**Comment by ArulselvanJaya** [comment]
This is my code, anything wrong

FROM webdevops/php-nginx-dev:7.2

ENV PHP_DISMOD=ioncube,redis,memcached,ldap,ioncube,imagick,pgsql,posix
ENV PHP_DATE_TIMEZONE=Asia/Kolkata

RUN docker-service enable postfix

**Comment by hhoechtl** [comment]
No your file is correct and works:

```
root@git /tmp/test # docker build -t sendmailtest .
Successfully built db39dd2c0ffb
Successfully tagged sendmailtest:latest
root@git /tmp/test # docker run -d --name sendmailtest sendmailtest
a2359d4fb28f5d77ffdaf4baaad8547ad7f739282ea18e596a4437db42e3a675
root@git /tmp/test # docker exec -ti sendmailtest bash
root@a2359d4fb28f:/# echo "Subject: sendmail test" | sendmail -v test@mail.com
Mail Delivery Status Report will be mailed to <root>.
```

**Comment by ArulselvanJaya** [comment]
But i am not getting mail.

**Comment by hhoechtl** [comment]
That's related to mailing in general, not our container or configuration.

Sendmail is available and does work. We do not give support for such deep issues with linux basics not related to our containers or their configuration.

If you want to send mail to gmail, you must have SPF, you should have DKIM and send a full mail with a domain matching the SPF record.

**Comment by ArulselvanJaya** [comment]
Thank you very much
