### ISSUE TITLE
make mysql-restore - No database selected

### ISSUE THREAD

**Issue by meronimo** [webdevops/Dockerfile#225]
Hi,

i'm running into some errors with the **_make mysql-restore_** command.

```
make mysql-restore
 * Starting MySQL restore...
ERROR 1046 (3D000) at line 1: No database selected
make: *** [mysql-restore] Error 1
```

Do i have to set **MYSQL_DATABASE** in the restore.sh?
is there another way to import my dump via **docker-entrypoint-initdb.d**

cheers!

**Comment by PanadeEdu** [comment]
I will close this.
