### ISSUE TITLE
Build process does not work

### ISSUE THREAD

**Issue by wadimdementjew** [webdevops/Dockerfile#230]
https://build.webdevops.io/

is the project no more maintained?

**Comment by erighetto** [comment]
@wadimdementjew I think you are right. I tried to set up my own an identical building environment to find a the problem and to propose a solution... but no luck.

**Comment by wadimdementjew** [comment]
the building environment also does not work for me, what works for me... (i need an php-nginx) build the php image on my own the classical way and then not extending from that image, i only change one line of code...
BUT this is not the solution for the main problem...

**Comment by athenaspa** [comment]
@mblaschke @guiyomh how can we help you to not abandon this usefull project?

**Comment by iamquan** [comment]
Please save this project : ((
PHP version hasn't updated for months.

**Comment by hhoechtl** [comment]
Thank you for all your feedback. We try to keep this project alive and will have a team hangout next week to discuss the future. Most likely I will provide a maintainer who can do this during work hours.

**Comment by PanadeEdu** [comment]
As the build process is working, I will close this ticket.
Related are Container Build Issues -> currently in work to be fixed
General Project Status -> #231
