### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by bemeyert** [webdevops/Dockerfile#231]
Hello all,
We are happily using your great images. We saw that the last update was some time ago and that all builds are failing too. Is this project in difficulties? Can we help?
Cheers

**Comment by hhoechtl** [comment]
Currently the main contributors are very busy. We're currently discussing resource management on reviving this project. PHP 7.2 and many other issues should be fixed.
Probably I will provide an employee who will be assigned some working time to maintain this project.

**Comment by bemeyert** [comment]
That doesn't (yet) sound very encouraging. It would be sad if this awesome project goes down and it would also mean a lot of work for us. So, anything we can do to help (as workforce, send beers etc.)?

**Comment by PanadeEdu** [comment]
Hi,

we just got a meeting done yesterday for this topic. We are now in the process how to structure the work so we can fix this. 

So there is indeed some progress. :)

**Comment by bemeyert** [comment]
Thx @PanadeEdu I'd appreciate if you can keep us posted.

**Comment by PanadeEdu** [comment]
Short Update: The Taskforce revived the build process. We go a fresh set of images pushed. 
We now check the packages and take a look to make New PHP Versions available.

**Comment by PanadeEdu** [comment]
We activated 7.2 containers and are currently trying to get a hold on the most common issues. 
Most appreciated would be if new issues are raised with real bugs and problems.

As this is just a discussion i would close this now. 
I consider the Project revived.
