### ISSUE TITLE
webdevops/php-nginx

### ISSUE THREAD

**Issue by ayrtck** [webdevops/Dockerfile#245]
how can i install redis-extend?
i can't find phpize.......
i need redis and memcached.

**Comment by ayrtck** [comment]
who can help me. I am a rookie:(

**Comment by hhoechtl** [comment]
Which tag of the image are you using? `webdevops/php-nginx:7.2` or `webdevops/php-nginx:ubuntu-16.04`?

Except for alpine (already fixed, but build is missing due to not working build server temporarily) all images currently already contain redis.
