### ISSUE TITLE
webdevops/php:centos-7-php7

### ISSUE THREAD

**Issue by ayrtck** [webdevops/Dockerfile#247]
ngxin 502.

**Comment by ayrtck** [comment]
Dockerfile just FROM webdevops/php:centos-7-php7. but 502

**Comment by hhoechtl** [comment]
The image you mentioned doesn't contain a nginx.
It's a PHP only image without webserver.

Could you provide more details?

**Comment by hhoechtl** [comment]
Closed due to inactivity
