### ISSUE TITLE
issue with docker-service trying to update nginx-php:alpine

### ISSUE THREAD

**Issue by stepps** [webdevops/Dockerfile#249]
We use webdevops nginx-php:alpine image extensively in our infrastructure.
Now one of our customers requires nginx version to be higher than 1.14. That nginx version is only available in alpine 3.8, so I set out to rebuild the image from bootstrap working my way up one from at the time.

Now I am completely stuck rebuilding php:alpine. "docker-service enable syslog" fails without any significant output. I would like to see the source of those scripts, but I haven't been able pinpoint it.

My understanding is that docker-service is a supervisord wrapper. I would like to adapt it to our needs

**Comment by hhoechtl** [comment]
The scripts you are looking for are located here: https://github.com/webdevops/Dockerfile/tree/master/provisioning/base/general/bin/usr-bin

and yes it's basically a supervisord wrapper.

**Comment by hhoechtl** [comment]
I tried it and the exit code returned by `docker-service enable syslog` is `1` but that doesn't make any sense, since every command executed on its own returns `0`.

I traced it down to the line `set -o pipefail` being the problem. But my knowledge of shell scripting isn't deep enough to figure out what causes this.

**Comment by hhoechtl** [comment]
We also encounter the issue with `ubuntu-18.04`

**Comment by bemeyert** [comment]
@hhoechtl When you use a pipe in Bash and one of the right handside comands fails but the last command succeeds the pipe is still successful. If you set `pipefail` the pipes will fail.
You can try to run the script with `set -x` to see what is happening.

**Comment by hhoechtl** [comment]
Thank you very much for the hint.

I found the issue:

```
> syslog-ng --version
syslog-ng 3 (3.13.2)
```

VS

```
> syslog-ng --version
syslog-ng 3.5.6
```

Therefore the regex used in the provisioning script:
```
SYSLOG_NG_VERSION=$(syslog-ng --version | grep -E -e '^syslog-ng[ ]+[0-9]+\.[0-9]+' | head -n 1 | awk '{print $2}' | cut -f 1,2 -d .)
```

is wrong

**Comment by bemeyert** [comment]
Maybe looking into the version of the Alpine pkg might help?
```
bash-4.3# apk info -e -d syslog-ng | grep ^syslog-ng
syslog-ng-3.9.1-r1 description:
```

**Comment by hhoechtl** [comment]
As the provisioning script is universal that's not possible, but I fixed it by using the line containing the `Installer-Version` which is syntactically identical across all distros.

**Comment by hhoechtl** [comment]
I tested the build of `webdevops/php:alpine` locally with `3.8` and it worked. Therefore I updated the version of our alpine images to `3.8` in https://github.com/webdevops/Dockerfile/commit/8d6b2e1e8ccafaa721e218c262aaeb9296e06184

The built images will soon be available.
