### ISSUE TITLE
Add phpunit?

### ISSUE THREAD

**Issue by mblaschke** [webdevops/Dockerfile#25]

**Comment by guiyomh** [comment]
hi, 

i work on a container that extend webdevops/php and add many tools to audit php code  :

- phploc
- pdepend
- phpmd
- phpcs
- phpcbf
- phpcpd
- phpdcd
- phpmetrics
- php-cs-fixer
- deprecation-detector (for symfony)
- php7cc

Are you interested ?

**Comment by mblaschke** [comment]
Maybe we should add a development image of all php* images with xdebug and other stuff.. would this be a better solution?

**Comment by guiyomh** [comment]
yes, i push my PR
