### ISSUE TITLE
how to build images with webdevops/dockerfile-build-env?

### ISSUE THREAD

**Issue by kaluzki** [webdevops/Dockerfile#254]
i tried to build this repo localy inside a "fwebdevops/dockerfile-build-env" container

setup & provision seems to work:
```bash
$ git clone git@github.com:webdevops/Dockerfile.git .
...
$ docker run -ti --rm -v $(pwd):/app -w /app webdevops/dockerfile-build-env bash
$ make setup

...

Bundled gems are installed into ./vendor.
$ make provision

...

> finished execution in 0:00:05 successfully
```

build, graph, and others fail:
```bash
$ make build
Executing docker:build (8 threads, 1 retries)

Starting execution of 322 tasks...
.  Pulling dependency images FAILED (duration: 0:00:00, #task 1/322, progress 0%)

-> finished 1 tasks

Task DependencyPuller (duration: 0:00:00):
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- ERROR OUTPUT --
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/app/bin/webdevops/taskloader/BaseTaskLoader.py", line 121, in task_runner
    status = func(task=task, *args)
  File "/app/bin/webdevops/taskloader/DockerBuildTaskLoader.py", line 119, in task_dependency_puller
    if not pull_image(image):
  File "/app/bin/webdevops/taskloader/DockerBuildTaskLoader.py", line 88, in pull_image
    tag=pull_image_tag,
  File "/app/bin/webdevops/docker/DockerCliClient.py", line 32, in pull_image
    return Command.execute(cmd)
  File "/app/bin/webdevops/Command.py", line 60, in execute
    env=env
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

:: end of output "DependencyPuller"


> finished execution in 0:00:00 with errors (exitcode 2)
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 2

$ make graph
Executing generate:graph (1 threads, 1 retries)


                                                                                                                                                                             
  [ExecutableNotFound]                                                                                                                                                       
  failed to execute ['dot', '-Tpng', '-O', '/app/documentation/docs/resources/images/docker-image-layout.gv'], make sure the Graphviz executables are on your systems' PATH  
                                                                                                                                                                             

generate:graph [-a|--all] [-o|--output OUTPUT] [-F|--format FORMAT] [-f|--filename FILENAME]

Makefile:59: recipe for target 'graph' failed
make: *** [graph] Error 1
```

**Comment by hhoechtl** [comment]
To use `build` and some other commands, you need a docker daemon.

Docker is not installed currently in the `webdevops/dockerfile-build-env` but I will craft a commit that does.

To use it, you must bind mount the socket of your docker daemon when running the container:
```
docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/app -w /app webdevops/dockerfile-build-env bash
```
**Be aware:** This will build the images on the docker daemon of your host system => overwrite present images etc.

To really do an isolated build, you would need to use the docker-in-docker mechanism and run a docker daemon inside your `dockerfile-build-env` container. But I'm actually not sure how to do that, but you could look it up: https://github.com/docker-library/docker/tree/595ad0c92090937dcb7c200900fb97e36d36c412/18.06/dind

**Comment by kaluzki** [comment]
I didn't mention it in my first comment, but I have already tried mounting docker socket into dockerfile-build-env container. It didn't solve the issue unfortunatelly.

Also calling `make graph`, i guess,  doesn't depend on the docker. It requires the `dot` executable, which is provided by `pgraphviz` package. After installing it with `apt-get install graphviz`, the call `make graph` works.

I have not tried that yet, but I believe the images can be built directly over the API instead of DIND.

Do you use this image internally to build your other images? Or how does it work?

**Comment by kaluzki** [comment]
Sorry,

I missed your last commit (b637237). Building images works now. Thank you!
However 'make graph' still fails.

**Comment by hhoechtl** [comment]
I just added graphviz to the image as well: https://github.com/webdevops/Dockerfile/commit/f101de53bb6f9b5cda2c715e64f60bba32a49377

The building is currently done by a Gitlab CI pipeline: https://gitlab.com/webdevops/autobuild

It basically runs a alpine docker image and installs only the basic dependencies, then we use `make setup` to install everything that is missing. 

So no, we don't use the dockerfile-build-env in our build process atm.
