### ISSUE TITLE
Don't install sodium extension alongside PHP 7.2

### ISSUE THREAD

**Issue by predakanga** [webdevops/Dockerfile#257]
The libsodium extension for PHP was recently added to the ubuntu based images (commit fb1cc4a6f4e820778f08f0eec22505c4ec66467a).

For PHP 7.1 that's a great move, but as of PHP 7.2 the extension is included in PHP itself.

This causes an error any time PHP is run: `PHP Fatal error:  sodium_init() in Unknown on line 0`

While the error is actually harmless, it's probably best not to install both versions.

**Comment by predakanga** [comment]
Forgot to include a way to replicate the issue:

    root@z-space:~# docker run --rm -i webdevops/php-nginx:ubuntu-18.04 php < /dev/null
    PHP Fatal error:  sodium_init() in Unknown on line 0
    root@z-space:~#

**Comment by hhoechtl** [comment]
Oh, thanks for pointing this out. Will solve this immediately.

**Comment by predakanga** [comment]
Thanks, and thanks for the work on the images - it's great appreciated!

**Comment by juanma386** [comment]
**sudo apt remove php-libsodium**
