### ISSUE TITLE
Does not support apache_request_headers function

### ISSUE THREAD

**Issue by toolowner** [webdevops/Dockerfile#260]
Hi,

The webdevops/php-apache-dev:5.6 does not support apache_request_headers function, while webdevops/php-apache-dev:debian-8 does.

I checked the Dockerfile of them but did not notice the difference between them. What make the debian-8 support apache_request_headers function but 5.6 does not?

Thank you.

**Comment by hhoechtl** [comment]
I also investigated but didn't find a clue where this function is coming from and why it's missing in the `webdevops/php-apache-dev:5.6` image. Sry.

**Comment by toolowner** [comment]
Thank you. For now, I'm using this workaround to be able to use php-apache-dev:5.6 (php-apache-dev:5.6 is better than php-apache-dev:debian-8).

```
if(!function_exists('apache_request_headers')) {
    function apache_request_headers() {
        $arh = array();
        $rx_http = '/\AHTTP_/';
        foreach($_SERVER as $key => $val) {
            if( preg_match($rx_http, $key) ) {
                $arh_key = preg_replace($rx_http, '', $key);
                //BEGIN restore the original letter case
                $rx_matches = array();
                $rx_matches = explode('_', $arh_key);
                if(count($rx_matches) > 0 && strlen($arh_key) > 2) {
                    foreach($rx_matches as $ak_key => $ak_val) $rx_matches[$ak_key] = ucfirst(strtolower($ak_val));
                    $arh_key = implode('-', $rx_matches);
                }
                //END restore the original letter case
                $arh[$arh_key] = $val;
            }
        }
        return $arh;
    }
}
```
