### ISSUE TITLE
Varnish image unmaintained?

### ISSUE THREAD

**Issue by bittner** [webdevops/Dockerfile#263]
I found the [webdevops/varnish](https://hub.docker.com/r/webdevops/varnish/) useful on Docker Hub. However, I noticed that the [builds are somewhat broken](https://hub.docker.com/r/webdevops/varnish/builds/) and there is [no Dockerfile content visible](https://hub.docker.com/r/webdevops/varnish/~/dockerfile/); at the same time, the image works and a tag seems to have been pushed just today.

What is the state of this image? Is it still maintained?

**Additional note:** I'm interested in (helping contribute) a Varnish Plus image to run validation of VCL files, also on [Varnish Plus](https://www.varnish-software.com/products/varnish-plus/) installations.

**Comment by hhoechtl** [comment]
The builds are not broken, they're just not done by dockerhub. As we build over 200 images every night and want to test them before deploying, we use our own build server (heavy Gitlab CI runner): https://gitlab.com/webdevops/autobuild/-/jobs/92534760.

So the image is maintained and has been pushed on the latest build 4 hours ago: https://hub.docker.com/r/webdevops/varnish/tags/

Feel free to contribute. If you need assistance, join our Slack channel: https://webdevops.io/slack/
