### ISSUE TITLE
php-apache(-dev) in Alpine with PHP 7.1

### ISSUE THREAD

**Issue by bemeyert** [webdevops/Dockerfile#267]
Hi all,

First thanks for reviving this project. Awesome work! Would it be possible to get an Alpine image with PHP 7.1? The thing is that 7.2 is a bit too fresh and a lot of applications don't work with it. I think the biggest problem is that Alpine itself no longer provides PHP 7.1 packages and completely switched to 7.2. We'd rather not use the Debian 7.1 image since it's just too big.

**Comment by hhoechtl** [comment]
It would be possible to build an Alpine image based on 3.7 since that's the last version of Alpine having PHP 7.1 as packages.

But how about the official PHP images? `webdevops/php-apache:7.1`?

**Comment by bemeyert** [comment]
Ok, I see. So either Alpine 3.7/PHP 7.1 or Debian/PHP 7.1., since webdevops/php-apache:7.1 is Debian-based. Ok, I take that into consideration. Thanks for your help.
