### ISSUE TITLE
Unable to install node

### ISSUE THREAD

**Issue by shyim** [webdevops/Dockerfile#276]
Start a container
```
docker run --rm -it webdevops/php-apache:7.2 bash
```

Execute in container
```
curl -sL https://deb.nodesource.com/setup_9.x | bash
```
```
+ apt-get install -y lsb-release > /dev/null 2>&1
Error executing command, exiting
```

Its failing to install lsb-release and dpkg is now broken
```
root@c375b98809ba:/# apt install
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```

```
root@c375b98809ba:/# dpkg --configure -a
dpkg: error: error creating new backup file '/var/lib/dpkg/status-old': Invalid cross-device link
```

**Comment by hhoechtl** [comment]
Usually I would recommend not to install node together in this container. Always use a second container for whatever purpose you need.
But it should of course be installable. I will investigate

**Comment by hhoechtl** [comment]
What might also be useful, on Docker for OSX we need to use `ini_set('xdebug.remote_host', 'host.docker.internal');`

**Comment by hhoechtl** [comment]
I tried this multiple times now:

```docker
FROM webdevops/php-apache:7.2

RUN apt-install lsb-release \
    && curl -sL https://deb.nodesource.com/setup_9.x | bash \
    && apt-install nodejs
```

and it worked all the time.

Small tip: using our `apt-install` wrapper script will save you time and it cleans up afterwards

**Comment by shyim** [comment]
Linux Kernel Issue with Docker yay. https://forums.docker.com/t/docker-fail-building-image-on-new-linux-kernel/62553
I am closing this then. Thanks for your help!
