### ISSUE TITLE
Get XDebug working with webdevops/php-apache-dev

### ISSUE THREAD

**Issue by Brewal** [webdevops/Dockerfile#277]
Hello,

> image : webdevops/php-apache-dev:7.2

I've been struggling a couple of hours trying to get XDebug connecting with VSCode on my windows host without success. I do succeed in making my php 7.2 installed on windows debugging well the same project with my IDE. I have about the same php.ini configuration in the container. 
VSCode starts listening without any errors, but breakpoints just don't break anything when I reload my app 😞 

Did I miss something ? 

**docker-compose.yaml**

    version: '3'
    services:
      web:
        image: webdevops/php-apache-dev:7.2
        ports:
         - "8000:80"
         - "9000:9000"
        volumes:
         - .:/var/www
         - ./vhosts:/opt/docker/etc/httpd/vhost.common.d
        environment:
          PHP_DISPLAY_ERRORS: 1
          XDEBUG_REMOTE_AUTOSTART: 1
          XDEBUG_REMOTE_CONNECT_BACK: 1
          XDEBUG_REMOTE_PORT: 9000

**debug console of vscode**

    <- launchResponse
    Response {
      seq: 0,
      type: 'response',
      request_seq: 2,
      command: 'launch',
      success: true }

**docker-compose ps**

    Le chemin d’accès spécifié est introuvable.
        Name                Command           State                           Ports
    -------------------------------------------------------------------------------------------------------
    apitest_web_1   /entrypoint supervisord   Up      443/tcp, 0.0.0.0:8000->80/tcp, 0.0.0.0:9000->9000/tcp

**php -i** (container)

    xdebug.auto_trace => Off => Off
    xdebug.cli_color => 1 => 1
    xdebug.collect_assignments => Off => Off
    xdebug.collect_includes => On => On
    xdebug.collect_params => 0 => 0
    xdebug.collect_return => Off => Off
    xdebug.collect_vars => Off => Off
    xdebug.coverage_enable => On => On
    xdebug.default_enable => On => On
    xdebug.dump.COOKIE => no value => no value
    xdebug.dump.ENV => no value => no value
    xdebug.dump.FILES => no value => no value
    xdebug.dump.GET => no value => no value
    xdebug.dump.POST => no value => no value
    xdebug.dump.REQUEST => no value => no value
    xdebug.dump.SERVER => no value => no value
    xdebug.dump.SESSION => no value => no value
    xdebug.dump_globals => On => On
    xdebug.dump_once => On => On
    xdebug.dump_undefined => Off => Off
    xdebug.extended_info => On => On
    xdebug.file_link_format => no value => no value
    xdebug.filename_format => no value => no value
    xdebug.force_display_errors => Off => Off
    xdebug.force_error_reporting => 0 => 0
    xdebug.gc_stats_enable => Off => Off
    xdebug.gc_stats_output_dir => /tmp => /tmp
    xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
    xdebug.halt_level => 0 => 0
    xdebug.idekey => docker => docker
    xdebug.max_nesting_level => 1000 => 1000
    xdebug.max_stack_frames => -1 => -1
    xdebug.overload_var_dump => 2 => 2
    xdebug.profiler_aggregate => Off => Off
    xdebug.profiler_append => Off => Off
    xdebug.profiler_enable => Off => Off
    xdebug.profiler_enable_trigger => On => On
    xdebug.profiler_enable_trigger_value => no value => no value
    xdebug.profiler_output_dir => /tmp/debug => /tmp/debug
    xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
    xdebug.remote_addr_header => no value => no value
    xdebug.remote_autostart => On => On
    xdebug.remote_connect_back => On => On
    xdebug.remote_cookie_expire_time => 3600 => 3600
    xdebug.remote_enable => On => On
    xdebug.remote_handler => dbgp => dbgp
    xdebug.remote_host => localhost => localhost
    xdebug.remote_log => no value => no value
    xdebug.remote_mode => req => req
    xdebug.remote_port => 9000 => 9000
    xdebug.remote_timeout => 200 => 200
    xdebug.scream => Off => Off
    xdebug.show_error_trace => Off => Off
    xdebug.show_exception_trace => Off => Off
    xdebug.show_local_vars => Off => Off
    xdebug.show_mem_delta => Off => Off
    xdebug.trace_enable_trigger => Off => Off
    xdebug.trace_enable_trigger_value => no value => no value
    xdebug.trace_format => 0 => 0
    xdebug.trace_options => 0 => 0
    xdebug.trace_output_dir => /tmp => /tmp
    xdebug.trace_output_name => trace.%c => trace.%c
    xdebug.var_display_max_children => 128 => 128
    xdebug.var_display_max_data => 512 => 512
    xdebug.var_display_max_depth => 3 => 3

**Comment by hhoechtl** [comment]
Did you change the DocRoot inside the container in your mounted `./vhosts:/opt/docker/etc/httpd/vhost.common.d`? Otherwise the docroot would be `/app` therefore your mount would not work.

We also set the variables for xdebug already, so you won't need to set them.

Did you configure the path mapping in your vscode (if you create a new php debugging configuration):
```json
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/app": "${workspaceRoot}"
            }
        },
```

**Comment by hhoechtl** [comment]
What might also be useful, on Docker for OSX we need to use ini_set('xdebug.remote_host', 'host.docker.internal');

**Comment by Brewal** [comment]
Thanks for the quick response. Indeed I do change the DocumentRoot inside my vhost : 

    ServerName api.apitest.localhost
    DocumentRoot /var/www/api/public

    DirectoryIndex index.php

    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    <IfModule mod_rewrite.c>
        RewriteEngine On

        RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
        RewriteRule ^(.*) - [E=BASE:%1]

        RewriteCond %{HTTP:Authorization} .
        RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

        RewriteCond %{ENV:REDIRECT_STATUS} ^$
        RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

        RewriteCond %{REQUEST_FILENAME} -f
        RewriteRule ^ - [L]

        RewriteRule ^ %{ENV:BASE}/index.php [L]
    </IfModule>

    <IfModule !mod_rewrite.c>
        <IfModule mod_alias.c>
            RedirectMatch 307 ^/$ /index.php/
        </IfModule>
    </IfModule>

This is my vscode config : 

        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "log": true
            "pathMappings": {
                "/var/www": "${workspaceRoot}"
            }
        }

I removed the port mapping 9000:9000 but that didn't seems to fix it. I'm not sure about the `remote_host` xdebug parameter ? shouldn't it be ignored when `remote_connect_back` is `On` ?

**Comment by Brewal** [comment]
Thanks for the link. I totally forgot about this windows and mac characteristic, as I'm more used to Linux!
I managed to make it work with this options in the `docker-compose.yaml` : 

    XDEBUG_REMOTE_CONNECT_BACK: 0
    XDEBUG_REMOTE_HOST: host.docker.internal

It seems a bit disappointing to have to make the configuration OS specific... I wonder if there is a way to configure docker to somewhat "forward" the real host IP so we can use `XDEBUG_REMOTE_CONNECT_BACK: 1`. 

But for now, I'm happy with this solution! Many thanks
