### ISSUE TITLE
[REQUEST] Add php7-imap to list of included php extensions

### ISSUE THREAD

**Issue by bkraul** [webdevops/Dockerfile#278]
This image has most all of the essential php extensions. However, some projects such as SuiteCRM require the php imap extension. It would be great if it was bundled with the php image and then be handled with the disabled ENV method if needed. I know we can build our own Dockerfile from the image, and I am currently doing just that, but it would be great to take advantage of the excellent update frequency devops already has.

Thank you for your set of images, they are excellent.

**Comment by hhoechtl** [comment]
I will take a look, shouldn't be to complicated to add it in every image.

**Comment by bkraul** [comment]
@hhoechtl You, sir, are a scholar and a gentleman. Appreciated. 👍

**Comment by hhoechtl** [comment]
The module has been added. If the build is working tonight, the images should be ready by tomorrow. Otherwise I'll have to investigate, but I already built some sample tags locally.

**Comment by bkraul** [comment]
Thanks again!

**Comment by hhoechtl** [comment]
Build successful. Case closed ;-)
