### ISSUE TITLE
Add amqp extension to php

### ISSUE THREAD

**Issue by vasilvestre** [webdevops/Dockerfile#294]
It require to `pecl install amqp` and `docker-php-ext-enable amqp`. Also apk add rabbitmq-c-dev is required

https://github.com/webdevops/Dockerfile/pull/295
https://github.com/webdevops/Dockerfile/pull/296

**Comment by hhoechtl** [comment]
Solved with https://github.com/webdevops/Dockerfile/commit/21716334938c8731fe92033c35924b24197aa998
