### ISSUE TITLE
Running as non root user broken

### ISSUE THREAD

**Issue by stijntilleman** [webdevops/Dockerfile#298]
This morning I was tinkering a little and while installing a composer dependency I noticed the `don't run composer as root message` which led go down the rabbit hole a little

```bash
$ docker run -it --rm -u 1000 webdevops/php-apache:7.2 whoami
root
```

```bash
$ docker run -it --rm -u 1000 webdevops/php:7.2 whoami
root
```

```bash
$ docker run -it --rm -u 1000 webdevops/php-official:7.2 whoami
root
```

The expected behaviour here would be `whoami: application` I guess

**Comment by hhoechtl** [comment]
The user flag is not working with our images due to the usage of `gosu`. See https://github.com/webdevops/Dockerfile/issues/226 for details.

**Comment by hhoechtl** [comment]
Should be resolved with https://github.com/webdevops/Dockerfile/pull/333
