### ISSUE TITLE
webdevops/bootstrap:alpine .inputrc for nicer human bash usage?

### ISSUE THREAD

**Issue by AlbinoDrought** [webdevops/Dockerfile#304]
[`webdevops/bootstrap:alpine`](https://github.com/webdevops/Dockerfile/blob/master/docker/bootstrap/alpine/Dockerfile) already has `bash` installed (which is great!) but there is no `inputrc` file (at `/etc/inputrc` or `~/.inputrc`), so shortcuts like `ctrl-leftarrow` and `ctrl-rightarrow` leave control codes like `;5D`, `;5C` instead of performing their expected functions:

![not working keybinds](https://user-images.githubusercontent.com/852873/55644011-77968500-5789-11e9-9e3b-9e929101c931.png)

If I copy [`/etc/inputrc` from my local fs](https://gist.github.com/AlbinoDrought/0b5409b63e3bcd408bc8ca8789123245) to the container, the keybinds work as expected. I'm not sure how common/abnormal/relevant my `/etc/inputrc` is.

![working keybinds](https://user-images.githubusercontent.com/852873/55644071-a14fac00-5789-11e9-907a-d63ecced711d.png)

Any chance we can get this file (not necessarily my `inputrc`, but some generic one) shoved in to the images by default, if this is not a breaking change? :smiley:

**Comment by bemeyert** [comment]
The only reason why Bash is in there is that the power of Bash scripts can be leveraged, compared to the default Alpine-Shell (ash?). Comfort on the command line is in my opinion not something this image should have. More parts, more work, more complex. The less parts, the less can breaknad the less maintenance is necessary. This image is supposed to run as a service. Work on the command line should be for debugging purposes only (if at all). And then I don't need a comfortable, tuned shell ;)

**Comment by hhoechtl** [comment]
Agree. Closed
