### ISSUE TITLE
apt-get update fails on jessie (debian8) based images

### ISSUE THREAD

**Issue by kaluzki** [webdevops/Dockerfile#305]
[jessie-updates has been removed](https://superuser.com/a/1417656/1020795)

```bash
$ docker run  webdevops/bootstrap:debian-8 cat /etc/apt/sources.list
deb http://deb.debian.org/debian jessie main contrib non-free 
deb http://security.debian.org/debian-security jessie/updates main
deb http://deb.debian.org/debian jessie-updates main
```

this line has to be replaced with something more suitable:

https://github.com/webdevops/Dockerfile/blob/d5a8e95d512056daaf21169ada9e75731369835d/docker/bootstrap/debian-8/Dockerfile#L51

**Comment by hhoechtl** [comment]
Already resolved
