### ISSUE TITLE
HTTP 503 info.php

### ISSUE THREAD

**Issue by imvieira** [webdevops/Dockerfile#307]
```$ docker run -ti -p 80:80 -p 443:443 -p 9000:9000 webdevops/php-apache:latest bash
/usr/sbin/apachectl start
echo index > /app/index.html
echo "<?php phpinfo();" > /app/info.php

WEB_ALIAS_DOMAIN='*.vm'
WEB_DOCUMENT_INDEX=index.php
WEB_DOCUMENT_ROOT=/app
WEB_PHP_SOCKET=127.0.0.1:9000
WEB_PHP_TIMEOUT=600
```

docker.vm:443 172.17.0.1 - - [18/Apr/2019:14:50:24 +0000] "GET /info.php HTTP/1.1" 503 734 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"

**Comment by imvieira** [comment]
docker image ls:
php                                7.2-cli             f8185c3c66e3        12 days ago         366MB

**Comment by hhoechtl** [comment]
Cannot reproduce

**Comment by imvieira** [comment]
Seems a typo in the command line ">":

```echo "<?php phpinfo();" > /app/info.php```
