### ISSUE TITLE
Enable TLS1.3

### ISSUE THREAD

**Issue by sharksforarms** [webdevops/Dockerfile#308]
I've tried enabling TLS1.3 by using this config: https://ma.ttias.be/enable-tls-1-3-nginx/

`nginx -t` returns an OK

But when making a tls1.3 request using `curl --tlsv1.3` I get:

```
[crit] 66#66: *1 SSL_do_handshake() failed (SSL: error 1417D102:SSL routines:tls_process_client_hello:unsupported protocol) while SSL handshaking
```

**Comment by hhoechtl** [comment]
That's because openssl still doesn't contain TLS 1.3. I'm not planing to compile openssl by myself. This will fix itself as soon as it's included in the lib. I recommend to use traefik or some other reverse proxy to terminate TLS1.3.
