### ISSUE TITLE
Passing in a liquibase.properties file

### ISSUE THREAD

**Issue by dpattermann-usgs** [webdevops/Dockerfile#309]
Hi, I'm looking to pass in a liquibase.properties file but it doesn't seem like that is possible with the way this is currently configured? Have you looked at adding that functionality in or is it already possible and I'm just not seeing it?

**Comment by jk3us** [comment]
I think this would be as easy as adding 

    if [[ -f liquibase.properties ]]; then
        cat liquibase.properties >> /liquibase.properties
    fi

after line 10 in https://github.com/webdevops/Dockerfile/blob/master/docker/liquibase/postgres/conf/bin/entrypoint.sh.  That way you start with the properties file in your project and can add values via the environment.

I haven't tried that yet though.

**Comment by dpattermann-usgs** [comment]
Instead of doing that, I changed line 10 from `echo -n > /liquibase.properties` to just copy in the liquibase file I wanted. Your change would also work well, thanks!
