### ISSUE TITLE
Ubuntu 17.04 docker container builds broken because of end of life

### ISSUE THREAD

**Issue by bweinzierl** [webdevops/Dockerfile#310]
Ubuntu 17-04 containers cannot build any more because of a missing file probably due to end of life for this release.
`E: The repository 'http://security.ubuntu.com/ubuntu artful-security Release' does not have a Release file.`

This line makes it work again for us:
`RUN sed -i -re 's/([a-z]{2}\.)?archive.ubuntu.com|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list`

I wanted to create a PR but don't know where i should put it. Dont want to mess with anything. There is some renaming going on in this file:
https://github.com/webdevops/Dockerfile/blob/master/docker/bootstrap/ubuntu-17.04/Dockerfile

@hhoechtl: I guess you know what to do :-)

**Comment by hhoechtl** [comment]
We're already doing those replacements and the build for 17.04 would work. We've just blacklisted it, since it's very old and deprecated and we have a lot of images to build.
