### ISSUE TITLE
Update nginx alpine to serve php 7.3

### ISSUE THREAD

**Issue by maciekpaprocki** [webdevops/Dockerfile#315]
php 7.3 is available now for some time and it is current stable version. When building alpine image I realised it is still using php7.2. Is there anyway to get php-nginx:alpine and php-nginx-dev:alpine with php7.3?

**Comment by hhoechtl** [comment]
PHP7.3 comes with `alpine:3.10`. I just upgraded to `alpine:3.9`. I will upgrade to `3.10` as soon as every php package is available (there are missing a few e.g. mongodb)

**Comment by maciekpaprocki** [comment]
I came back to that. It seems like alpine 3:10 removed mongo as well as few other packages due to licensing issues. 

https://github.com/docker-library/mongo/issues/324
https://gitlab.alpinelinux.org/alpine/aports/issues/10221

Quite possibly those packages will never be updated. Is there any easy workaround for people that don't need to those packages without building our own images?

**Comment by hhoechtl** [comment]
We can introduce a new image branch name `alpine-php73` or something like that. Feel free to create a PR

**Comment by maciekpaprocki** [comment]
Ok. Not sure if I necessarily know how to, but will give it a go :)
