### ISSUE TITLE
Install php-imagick 

### ISSUE THREAD

**Issue by RogerSik** [webdevops/Dockerfile#320]
With php-apache:7.3 currently (02.09.2019) there is no php7-imagick installed and custom installation (for testing) fails

~~~
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7-imagick
root@049af929c383:/#
~~~

Searching on this issue like #255 and others it seems that it was earlier installed and enabled.

**Comment by hhoechtl** [comment]
We inherit from the official PHP image `php:7.3-fpm-stretch`. It doesn't contain imagick and I didn't find a way to install it.
If you do so please tell me and I'll add it.

**Comment by RogerSik** [comment]
@hhoechtl got it working:

~~~
apt-get install libmagick++-dev
pecl install imagick
~~~

Add in **/usr/local/etc/php/conf.d/imagick.ini**
~~~
extension=imagick.so
~~~

**Comment by RogerSik** [comment]
Sucessfully did it with  php-apache:7.2 and 7.3

**Comment by hhoechtl** [comment]
Oh I forgot to check pecl. Maybe next week I'll find some time to implement
this.

Von unterwegs gesendet

Roger <notifications@github.com> schrieb am Di., 3. Sep. 2019, 15:46:
