### ISSUE TITLE
client_max_body_size in conf.d overwritten by vhost.common.d/10-general.conf

### ISSUE THREAD

**Issue by UeliDeSchwert** [webdevops/Dockerfile#321]
Hey there

I just spent a few hours trying to increase the `client_max_body_size`, but it always stayed at around 50M.

I tried to set the variable by mounting a .conf-file to `/opt/docker/etc/nginx/conf.d`.

Using `nginx -T` i created a dump of the generated config. There I saw that my file was being loaded, but further down the line the file `/opt/docker/etc/nginx/vhost.common.d/10-general.conf` was loaded and the only content of this file is `client_max_body_size 50M;`.

This means, it is in the current `latest` version not possible to increase the client_max_body_size unless one overwrites the mentioned file `10-general.conf` by mounting another one on top.

I don't think this is intended behaviour, because it is not mentioned anywhere in the docs.
Is there any reason why this file exists or sets a body size, thereby overwriting the server wide body size config?

I only used three relevant environment variables:
`WEB_DOCUMENT_ROOT=/app/public`
`PHP_POST_MAX_SIZE=500M`
`PHP_UPLOAD_MAX_FILESIZE=500M`

But I don't think that any of these settings should create this file.

The image is the current `latest` with hash `59c1c87c3474`. 

Thanks for an answer and thank you for the great work. If you need more information, just contact me.

**Comment by hhoechtl** [comment]
This has been introduced 2 years ago by @mblaschke and has never been re-thought until now.
I think it makes sense to introduce a new variable to configure the `client_max_body_size` in nginx.

**Comment by h1100e** [comment]
My project in google could platform k8s env.I use command to ovewrwrite the /opt/docker/etc/nginx/vhost.common.d/10-php.conf  file , add nginx params,and the pod can not running. What have I do?
