### ISSUE TITLE
Add yarn to image?

### ISSUE THREAD

**Issue by RogerSik** [webdevops/Dockerfile#322]
Is it possible to add yarn to the image? Without the need to do itself.

**Comment by hhoechtl** [comment]
Which image? We want to keep the images as small as possible but to contain
all necessary features. So e.g. a PHP image should not and will not contain
nodejs and yarn.

Roger <notifications@github.com> schrieb am Di., 3. Sep. 2019, 15:58:

**Comment by RogerSik** [comment]
@hhoechtl  for php-apache:7.2 we wanted to have it. 

But we had others problem with the setup with Akeneo in Docker so we went the oldschool way.

**Comment by hhoechtl** [comment]
Sorry, but the requirement of nodejs is so special, that's nothing we would include in the images by default. You have to build your own image that extends `php-apache:7.2` with nodejs and every module you need to run akeneo.

Actually akeneo is building their own images, so why not use them? They include anything you need.

**Comment by RogerSik** [comment]
Yes you are right, I can build it itself, but a ready image is always nicer to pull instead to build. :D 

The Akeneo image works sometimes not and they are writting to not use them for production so i prefer to choose a well documented image, which i can for almost all of my docker-compose webserver builds instead to use countless different.

**Comment by RogerSik** [comment]
Regardless that it is not integrated many thanks to your and your mantainer for this project, it makes many easier! :)
