### ISSUE TITLE
Install newer libsodium version

### ISSUE THREAD

**Issue by RogerSik** [webdevops/Dockerfile#323]
For **php-apache:7.2** is libsodium in version **1.0.11** installed. For the newest Magento 2.3.2 version libsodium atleast **1.0.13 is requiered**.

Is there a way to update it in the official image (for everyone)? 

See also https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.2OpenSource.html

> Issue: The security enhancements that are part of Magento 2.3.2 require the installation of libsodium version 1.0.13 or higher. You will not be able to successfully install Magento Commerce 2.3.2 without first ensuring that your server runs version 1.0.13 or higher. See Libsodium releases for a description of the available releases and installation instructions.

**Comment by hhoechtl** [comment]
Sorry, we only extend the official `php:7.2-fpm-stretch` image, which comes with `1.0.11`.
I've checked the libsodium documentation on how to install the new version and it would be quite some effort to get this into our build process.
As I'm not doing Magento (Shopware rocks ;-)), I'm not willing to invest my time on this one.
I would estimate it takes up to 1-2 days for someone, who is not yet familiar with the structure of this repository, to get this clean and running within our structure, so feel free to build this and issue a PR. If you have questions I'm willing to assist.
