### ISSUE TITLE
Please add postgresql-client

### ISSUE THREAD

**Issue by agilov** [webdevops/Dockerfile#324]
You have mysql client pre installed in your images. Please add also postgresql-client.

I am using postgresql in every project and image rebuilds are slow because of postgresql-client installation on dev environments.

**Comment by hhoechtl** [comment]
The images already contain `pgsql` PHP libraries. The `mysql-client` application is installed nowhere.

**Comment by agilov** [comment]
I mean from within container I have to use such thing:
`
# Check for main database is up
until PGPASSWORD=$DB_PASSWORD psql -p "$DB_PORT" -h "$DB_HOST" -U "$DB_USER" -c '\q'; do
  >&2 echo "Database is unavailable - sleeping"
  sleep 1
done

echo "Bootstrap..."

To make sure that database container is up and ready to accept connections. And this requires psql executable (postgresql-client). 
`

**Comment by hhoechtl** [comment]
Sorry but this tool is not necessary and we want to keep the images small. I propose you should build your own base image based on the webdevops images and go from there.

**Comment by agilov** [comment]
Ok. Thank you.
