### ISSUE TITLE
DocumentRoot in apache is not able to follow symlinks

### ISSUE THREAD

**Issue by mstenz** [webdevops/Dockerfile#328]
Hi, 
i have mounted directory in my container as /app for apache and there are some softlinks added in this directory, example

> lrwxrwxrwx  1 root root     54 Oct  7 15:46 t3lib -> /storage/efs-cl01/services/typo3o/html/typo3_src/t3lib/
> lrwxrwxrwx  1 root root     54 Oct  7 15:46 typo3 -> /storage/efs-cl01/services/typo3o/html/typo3_src/typo3/
> drwxr-xr-x  4 root root   6144 Oct  7 15:12 typo3conf/
> lrwxrwxrwx  1 root root     55 Oct  7 15:45 typo3_src -> /storage/efs-cl01/services/typo3o/html/typo3_src-4.6.18/
> drwxr-xr-x  4 root root   6144 Oct  7 15:16 typo3_src-4.6.18/

But webdevops configuration seems not to allow Symlinks to follow as i receive the following message in the log:
`AH00037: Symbolic link not allowed or link target not accessible: /app/index.php`

How I can configure the container to allow FollowSymlinks for the DocumentRoot? 
Please note, that I use swarm and cannot change existing files, only thing i can do is mount additional configuration files if required. 
thank you.

**Comment by hhoechtl** [comment]
Could you please provide the full `docker-compose.yml` that you are using.
Looks like you might have multiple issues:
* Missing `/storage` mount
* Permission problems with `/app`

The container does follow symlinks if they are accessible.

**Comment by mstenz** [comment]
Hi, i have not used any docker-compose file. but I fixed the issue now by not using direct full path when creating the symlink. Using only relative path works now.
