### ISSUE TITLE
PHP 5.6 imagick

### ISSUE THREAD

**Issue by marcobraghim** [webdevops/Dockerfile#336]
Hey, first of all thanks for providing all this containers that has help a lot. 

I need that the package imagick to be available. Tried to install it in the Docker file with commands like 'RUN set -x && apt-install php5-imagick' but without success.

Is there a way to get this package? How?

**Comment by hhoechtl** [comment]
Which 5.6 image are you referring to? `webdevops/php:5.6`? It already contains imagick.

If you want to install it manually, imagick is managed via pecl => `pecl install imagick`

**Comment by marcobraghim** [comment]
"Which 5.6 image are you referring to? webdevops/php:5.6? It already contains imagick."

So why I can't use Imagick in my code? Do I have to do something to enable it?

I'll try to install with pecl as you say and come back to say if works.

**Comment by marcobraghim** [comment]
It works with the command into Dockerfile `RUN apt-install libmagickwand-dev && pecl install imagick` and `extension=imagick.so` into php.ini.

Thank you very much
