### ISSUE TITLE
[nginx-php] Running locally

### ISSUE THREAD

**Issue by Vlad-Vekslyer** [webdevops/Dockerfile#338]
Hello! I'm having trouble running the container on localhost. I'm running the container with the command:
`docker run --name bp -e "WEB_DOCUMENT_ROOT=/app/public" -e "WEB_ALIAS_DOMAIN=localhost" -d my-app`

I'm not receiving any response when I send a request to localhost and the container doesn't generate any logs.

Here's the Dockerfile for my-app:
`FROM webdevops/php-nginx

COPY . ./app`

Could you please advise on how I can run the container locally? Thank you

**Comment by hhoechtl** [comment]
You forgot to expose a port: `docker run ... -p 8080:80`. Then you can use http://localhost:8080.

But I recommend a universal reverse proxy like https://github.com/codekitchen/dinghy-http-proxy or traefik where you can use ports 80 and 443 once and all containers are available through real hostnames locally which is controlled via labels or environment variables.
