### ISSUE TITLE
Shell into debian-7

### ISSUE THREAD

**Issue by sundarv85** [webdevops/Dockerfile#345]
When I run the below command, it just abruptly exits for `debian-7`, but the same works for `ubuntu-14.04, ubuntu-12.04, debian-8`

```
-> # docker run -it webdevops/php:debian-7 /bin/bash
Unable to find image 'webdevops/php:debian-7' locally
debian-7: Pulling from webdevops/php
39e552a2b1f7: Pull complete 
63c34d658d76: Pull complete 
a9e1c6d5ada1: Pull complete 
7fbbbed7d488: Pull complete 
235b2db8f5f4: Pull complete 
fdb4b0a9e6ef: Pull complete 
891eac987921: Pull complete 
f2368de6aec7: Pull complete 
b7a65ce8a5f3: Pull complete 
Digest: sha256:59c2067e3af9caaa180d3edf1d4774efa3f40a23a308b5718d4ad3b7187426a2
Status: Downloaded newer image for webdevops/php:debian-7

-> # 
```

```
-> # docker run -it webdevops/php:ubuntu-12.04 /bin/bash
Unable to find image 'webdevops/php:ubuntu-12.04' locally
ubuntu-12.04: Pulling from webdevops/php
d8868e50ac4c: Pull complete 
83251ac64627: Pull complete 
589bba2f1b36: Pull complete 
d62ecaceda39: Pull complete 
6d93b41cfc6b: Pull complete 
63c34d658d76: Pull complete 
fa3d41b817e0: Pull complete 
6be224a5d147: Pull complete 
8e3dc7a64ec3: Pull complete 
c433c31571f5: Pull complete 
a00bb25bfc27: Pull complete 
c4d5db2f7b23: Pull complete 
301936d61a2c: Pull complete 
Digest: sha256:816cb80b5a0cf1b18f3279c34297e59d8cb046c516c09dac49455e7318568d04
Status: Downloaded newer image for webdevops/php:ubuntu-12.04
root@9ac3ec06397e:/# 
```

Any thoughts as to why..

Also, I'm looking for glibc-2.13 in any of the PHP builds, as I need to build an extension on it and `ubuntu-12.04` image only has glibc-2.15.. are there any older dockers files that has previous glibc versions..

**Comment by hhoechtl** [comment]
Sorry we don't support those ancient things any more.

**Comment by sundarv85** [comment]
Got it. I found the solution from the following links:

- How to run it in linux
https://www.juliogonzalez.es/debian-10-some-docker-containers-are-not-starting/471

- How to update new packages
https://serverfault.com/questions/960970/wheezy-updates-on-archive-debian-org-returns-404-not-found

- How to ignore the expired message in apt-get update
https://unix.stackexchange.com/questions/2544/how-to-work-around-release-file-expired-problem-on-a-local-mirror

For anyone else who needs something `ancient` ;)
