### ISSUE TITLE
Update Alpine bootstrap version (Alpine3.11/PHP7.3)

### ISSUE THREAD

**Issue by kohlerdominik** [webdevops/Dockerfile#346]
Hi

We are using `php-nginx:alpine-php7` image. It uses Alpine3.9 and php7.2, which both are 2 versions behing the latest version of each. Active support for php7.2 [ended half a year ago](https://www.php.net/supported-versions.php), with security updates ending in 7 months.

From #315 i understand, that updating to php7.3 seems not possible without breaking some packages. However, looking forwards to the end of support we would like to update the dependency in near feature.

As i assume this Repo will not distribute unsupported versions, i wanted to ask what the Roadmap for `php-nginx:alpine-php7` and similar images is.

Besides of that, I also wanted to thank for the great work done here, very much appreciated!

**Comment by hhoechtl** [comment]
I had some time over easter. The outcome is that the following images are DEPRECATED and not longer built automatically:

* `webdevops/php:alpine`
* `webdevops/php:alpine-3`
* `webdevops/php:alpine-3-php7`
* `webdevops/php-dev:alpine`
* `webdevops/php-dev:alpine-3`
* `webdevops/php-dev:alpine-3-php7`
* `webdevops/php-apache:alpine`
* `webdevops/php-apache:alpine-3`
* `webdevops/php-apache:alpine-3-php7`
* `webdevops/php-apache-dev:alpine`
* `webdevops/php-apache-dev:alpine-3`
* `webdevops/php-apache-dev:alpine-3-php7`
* `webdevops/php-nginx:alpine`
* `webdevops/php-nginx:alpine-3`
* `webdevops/php-nginx:alpine-3-php7`
* `webdevops/php-nginx-dev:alpine`
* `webdevops/php-nginx-dev:alpine-3`
* `webdevops/php-nginx-dev:alpine-3-php7`

You shall use the new images which are based on the official `php:7.(1|2|3|4)-fpm-alpine` images.

* `webdevops/php:7.1-alpine`
* `webdevops/php:7.2-alpine`
* `webdevops/php:7.3-alpine`
* `webdevops/php:7.4-alpine`
* `webdevops/php-dev:7.1-alpine`
* `webdevops/php-dev:7.2-alpine`
* `webdevops/php-dev:7.3-alpine`
* `webdevops/php-dev:7.4-alpine`
* `webdevops/php-apache:7.1-alpine`
* `webdevops/php-apache:7.2-alpine`
* `webdevops/php-apache:7.3-alpine`
* `webdevops/php-apache:7.4-alpine`
* `webdevops/php-apache-dev:7.1-alpine`
* `webdevops/php-apache-dev:7.2-alpine`
* `webdevops/php-apache-dev:7.3-alpine`
* `webdevops/php-apache-dev:7.4-alpine`
* `webdevops/php-nginx:7.1-alpine`
* `webdevops/php-nginx:7.2-alpine`
* `webdevops/php-nginx:7.3-alpine`
* `webdevops/php-nginx:7.4-alpine`
* `webdevops/php-nginx-dev:7.1-alpine`
* `webdevops/php-nginx-dev:7.2-alpine`
* `webdevops/php-nginx-dev:7.3-alpine`
* `webdevops/php-nginx-dev:7.4-alpine`

I did not build 7.0 as many libs are different from the newer versions and 7.0 is EoL for quite some time already.
