### ISSUE TITLE
Question -> Running custom script after container is built

### ISSUE THREAD

**Issue by realnsleo** [webdevops/Dockerfile#348]
Hello,
I am quite new to Docker and I am using the webdevops:php-nginx image to run my application. There are some scripts that I need to run right after the container has been built. I was wondering what the best way to do that would be. This is my Dockerfile:

    FROM webdevops/php-nginx:7.4
    COPY --chown=application:application . /app
    WORKDIR /app
    COPY mycustomscript.sh /opt/docker/provision/entrypoint.d/mycustomscript.sh
    RUN chmod +x /opt/docker/provision/entrypoint.d/mycustomscript.sh
    ENTRYPOINT ['entrypoint.sh']

This is my bash script (mycustomscript.sh)
    #!/bin/bash
    php /app/artisan migrate --seed

When the container builds successfully, I get an error saying `entrypoint.sh` not found. I would appreciate any help in solving this. Thank you for your time.

**Comment by hhoechtl** [comment]
You don't need to set `ENTRYPOINT` that is inherited from the parent image and will be correctly executed.

As you noticed correctly, you just have to place your custom script inside the correct script folder and it will be executed automatically.

You can look up how this works here: https://github.com/webdevops/Dockerfile/tree/master/provisioning/base/general/bin

One side note: It's dangerous to assume that your database is up and running on container startup => `migrate --seed` propagates a laravel database if I'm correct. You should have either a wait for database or skip on error handling in your script.

**Comment by realnsleo** [comment]
Thanks @hhoechtl, it's very clear now. And thanks for the point put on the database migration, I will find a much better way to address it. Thanks again.
