### ISSUE TITLE
php-apache:7.3: Akeneo4 Warning about icu system and intl php extension up-to-dateness

### ISSUE THREAD

**Issue by RogerSik** [webdevops/Dockerfile#350]
Following warning message i got with Akeneo 4 and the installation check command (pim:installer:check-requirements)

![Bildschirmfoto 2020-04-15 um 12 10 51](https://user-images.githubusercontent.com/165814/79345147-07404900-7f31-11ea-8484-8fe3a7c914fa.png)

Is here Akeneo 4 too much fastidious or can we update the mention packages? 

Used Image is webdevops/php-apache:7.3

**Comment by hhoechtl** [comment]
The image contains the official `intl` package which comes bundled with the `php:7.3-fpm` image.
Looks like they are outdated by distribution.

I'll have to check how I can manually install a newer version (maybe via pecl or something like that)

**Comment by hhoechtl** [comment]
In the next build there will be version 66.1 of ICU included (manually compiled).

**Comment by RogerSik** [comment]
Nice awesome work you are doing! 👍
