### ISSUE TITLE
Not all XDEBUG environment variable are setup

### ISSUE THREAD

**Issue by RogerSik** [webdevops/Dockerfile#351]
With docker-compose we used an extra file for XDEBUG 
```
     env_file:
      - .env.appserver
```
and following enviromment variable is setup in the mention file. # are comments

```
# https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache-dev.html
# XDEBUG
PHP_DEBUGGER=xdebug
XDEBUG_REMOTE_HOST=10.101.66.238
XDEBUG_REMOTE_CONNECT_BACK=true
XDEBUG_MAX_NESTING_LEVEL=3000 # didn't work
XDEBUG_REMOTE_ENABLE=true
XDEBUG_IDE_KEY=PHPSTORM # didn't work
```

We tested the setup variables with ```php -i``` and the variables with the # didn't work was visible that they didn't got changed. 

```
# php -i 
debug.idekey => docker => docker
xdebug.max_nesting_level => 1000 => 1000
```

We are using webdevops/php-apache:7.3

**Comment by RogerSik** [comment]
We helped us now with following variable
```
XDEBUG_CONFIG='remote_host=10.101.66.238 idekey=PHPSTORM max_nesting_level=3000'
```

**Comment by hhoechtl** [comment]
True, there's a conflict between the files `bootstrap.d/20-php-module-xdebug.sh` and `entrypoint.d/10-php-debugger.sh` during the provisioning phase.

I'll check in detail soon.

**Comment by hhoechtl** [comment]
Oh sry, it's just missing.

**Comment by Orfeu24** [comment]
Hello, it seems that XDEBUG_IDE_KEY is still missing at least in this version : [php-apache-dev/8.3](https://github.com/webdevops/Dockerfile/blob/master/docker/php-apache-dev/8.3/conf/provision/entrypoint.d/10-php-debugger.sh)

Thank you
