### ISSUE TITLE
Define logrotate config

### ISSUE THREAD

**Issue by Propaganistas** [webdevops/Dockerfile#356]
Hi

I'm exploring the options to define some additional logrotate configurations.
I've tried putting a conf file in `/opt/docker/etc/logrotate.d` (similar to `supervisor` and `cron` configurations), but that doesn't seem to work.

As we speak I'm now running a build where I put a file in `/etc/logrotate.d`.

Is this a candidate for alignment so it can be configured in `/opt/docker` just like other services?

**Comment by vlauciani** [comment]
Hi @Propaganistas 

How did you solved this issue? I was thinking to run `logrotate` by `crontab` line; could it be a good solution?

Thank you.
