### ISSUE TITLE
php-nginx:7.2: how to not require .php in url

### ISSUE THREAD

**Issue by arthurpankiewicz** [webdevops/Dockerfile#368]
I have a docker that is based off of `webdevops/php-nginx:7.2` and I am trying to configure the nginx to route requests with or without the .php extension to the appropriate file.

If `abc.php` exists, I need `/abc` and `/abc.php` to route to `abc.php`. Everything else would go to `index.php`

Current setup looks like:

`Dockerfile` contains
```
WEB_DOCUMENT_ROOT=/app/public
COPY docker/opt/docker/etc /opt/docker/etc/
```

`opt/docker/etc/nginx/conf.d/10-location-root.conf`
```
server {
  index index.html index.php;
  location / {
    try_files $uri $uri/ /index.php?_url=$uri&$args;
  }
}
```

`/app/public` contains
```
index.php
abc.php
```

Currently this configuration routes everything to `index.php` except for `/abc.php`. Trying to hit `/abc` routes to `index.php`.

Thanks :)

**Comment by seanpmgallagher** [comment]
@arthurpankiewicz this issue was marked as closed but without a solution. What would be the command required as current builds do not act in the way above.
