### ISSUE TITLE
composer 2.0 was released

### ISSUE THREAD

**Issue by ChrisB9** [webdevops/Dockerfile#369]
This weekend composer got released: `2.0.2 - released 2020-10-25` 

That means, that with the next build the following line will automatically update the composer version to 2.0.x  
`curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer`

The issue is, that older projects running with these Dockerfiles will have troubles as they might not be PSR-compliant or they use composer-plugins that are not updated yet (or never will be). 

I suggest, we add a second line to the jinja-Templates, that provide composer1.0 as an alternative option, like this:  
`curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer1 --version=1.10.16`

That way new projects and compliant projects can use and enjoy the magic of composer2 but older applications still have the possibility to be updated and maintained until they either fade out or will become compliant.

If there is an interest in this solution I could open a pull request this week to provide this functionality.

**Comment by hhoechtl** [comment]
Sounds like a great idea, would appreciate it

**Comment by calebfavor** [comment]
This automatic composer upgrade has been causing problems in some of our projects. I think a solution where we can use an environment variable to control the installed version would be better. I do not have the bash chops to submit PR unfortunately.

**Comment by hhoechtl** [comment]
I'll introduce `COMPOSER_VERSION` ENV variable which defaults to "2". An entrypoint script will set the symlink to the composer version accordingly.

**Comment by hhoechtl** [comment]
Works:

``` 
~/.../webdevops/Dockerfile >>> docker run --rm webdevops/php:7.2-alpine composer --version
Composer version 2.0.2 2020-10-25 23:03:59
~/.../webdevops/Dockerfile >>> docker run --rm -e COMPOSER_VERSION=1 webdevops/php:7.2-alpine composer --version
Composer version 1.10.16 2020-10-24 09:55:59
```

**Comment by hhoechtl** [comment]
Closed with https://github.com/webdevops/Dockerfile/commit/c8e6bb53597e106f37076ecfb90b19c0dcc60348

**Comment by leonidd-hyuna** [comment]
while running with docker-compose COMPOSER_VERSION is set to 1 in multiple places including Dockerfile but there is no composer while running with `docker-compose build`

```
worker$ docker-compose build --no-cache
rabbitmq uses an image, skipping
Building app
Step 1/4 : FROM webdevops/php-dev:7.4
 ---> 8c8243c43e82
Step 2/4 : ENV COMPOSER_VERSION=1
 ---> Running in 39fd6843503b
Removing intermediate container 39fd6843503b
 ---> 981df9879e5f
Step 3/4 : RUN echo env-composer-version ${COMPOSER_VERSION}
 ---> Running in a88f71f3c4a4
env-composer-version 1
Removing intermediate container a88f71f3c4a4
 ---> 930eb06ada44
Step 4/4 : RUN composer --version
 ---> Running in ebf62ca99927
/bin/sh: 1: composer: not found
ERROR: Service 'app' failed to build : The command '/bin/sh -c composer --version' returned a non-zero code: 127

```

**Comment by calebfavor** [comment]
I have the same issue: [Commit](https://github.com/webdevops/Dockerfile/commit/c8e6bb53597e106f37076ecfb90b19c0dcc60348#commitcomment-43630704)
