### ISSUE TITLE
there is no composer while building container

### ISSUE THREAD

**Issue by leonidd-hyuna** [webdevops/Dockerfile#374]
https://github.com/webdevops/Dockerfile/blob/8f981bb239945b9d73c19f482c5fa52089693494/docker/php-official/7.4/conf/provision/entrypoint.d/20-php.sh#L75

composer is not working WHILE BUILDING CONTAINER

while running with docker-compose COMPOSER_VERSION is set to 1 in multiple places including Dockerfile and docker-compose.yml file but there is no composer while running with docker-compose build

```
worker$ docker-compose build --no-cache
rabbitmq uses an image, skipping
Building app
Step 1/4 : FROM webdevops/php-dev:7.4
 ---> 8c8243c43e82
Step 2/4 : ENV COMPOSER_VERSION=1
 ---> Running in 39fd6843503b
Removing intermediate container 39fd6843503b
 ---> 981df9879e5f
Step 3/4 : RUN echo env-composer-version ${COMPOSER_VERSION}
 ---> Running in a88f71f3c4a4
env-composer-version 1
Removing intermediate container a88f71f3c4a4
 ---> 930eb06ada44
Step 4/4 : RUN composer --version
 ---> Running in ebf62ca99927
/bin/sh: 1: composer: not found
ERROR: Service 'app' failed to build : The command '/bin/sh -c composer --version' returned a non-zero code: 127
```

**Comment by adambisek** [comment]
I am adding it like this:

```
FROM webdevops/php-nginx:7.4-alpine

ENV COMPOSER_VERSION="1"
WORKDIR /app

RUN apk add composer
```

But then fails entrypoint
```
Log stdout redirected to /proc/1/fd/1
Log stderr redirected to /proc/1/fd/2
-> Executing /opt/docker/provision/entrypoint.d/05-permissions.sh
-> Executing /opt/docker/provision/entrypoint.d/20-nginx.sh
-> Executing /opt/docker/provision/entrypoint.d/20-php-fpm.sh
-> Executing /opt/docker/provision/entrypoint.d/20-php.sh
ln: /usr/local/bin/composer: File exists
```

**Comment by leonidd-hyuna** [comment]
to avoid Symlink error 
this line 
` ln -s /usr/local/bin/composer${COMPOSER_VERSION:-2} /usr/local/bin/composer`

can be changed with -f or -T key to create symlink with force

**Comment by leonidd-hyuna** [comment]
> But then fails entrypoint on container start

I think as a temporary fix we can remove composer after installing packages, but it is a really bad way

**Comment by adambisek** [comment]
Yes, agree, but these are workarounds only.

**Comment by hhoechtl** [comment]
Fixed with https://github.com/webdevops/Dockerfile/commit/40305a2a77c845356cca3ab005cf2ea5abffe927 (build pending, approx 1 hour)

**Comment by adambisek** [comment]
Works, thank you!

**Comment by mgrundkoetter** [comment]
No, it does not work. Can you please post a working Dockerfile config? Whenever I use composer install in the Dockerfile, composer2 is used, no matter where the ENV var is set...

**Comment by hhoechtl** [comment]
@mgrundkoetter ENV vars are not evaluated during build process.

Therefore:
```
FROM webdevops/php:7.4
COPY ./src /app
RUN composer1 install -d /app
```

The ENV variable is evaluated on container start (entrypoint) and switches the symlink to the composer version. During build time that symlink remains on composer2 (but it is present since 40305a2).

**Comment by mgrundkoetter** [comment]
Yes, after a deep dive into the _Dockerfile_ at `https://github.com/webdevops/Dockerfile/blob/master/docker/php-official/7.3-alpine/Dockerfile` I saw this now. It would be VERY helpful to add this information to the docs as trying around with the `ENV` var in _docker-compose_ file, as `--build-args` during `docker build` and `ENV` setting in the _Dockerfile_ takes quite some time. Which could be saved complete if one did know the binaries are BOTH there, just named `composer1` and `composer2`
