### ISSUE TITLE
Directory Listing turned on

### ISSUE THREAD

**Issue by ja-weber** [webdevops/Dockerfile#379]
Hello,
I am using this version webdevops/php-apache:7.4 and the webserver directory listing is turned on. Is that normal?

Br
Jweb

**Comment by hhoechtl** [comment]
Yes that is default. If you want to change it, configure apache.

The config file is located in `/opt/docker/etc/httpd/conf.d/10-server.conf`. Either modify it by replacing it during a `docker build` or overmount it on container start.

**Comment by ja-weber** [comment]
Thanks for the response. The container is for production use or not? Is it not a security issue?

**Comment by hhoechtl** [comment]
Issue was not raised until now, but you got a point there. I just changed it
