### ISSUE TITLE
add PHP8

### ISSUE THREAD

**Issue by Ferikl** [webdevops/Dockerfile#380]
Hey guys! Thanks for great job!!
Recently PHP8 https://www.php.net/releases/8.0/en.php has been released. Can you add new version support.

**Comment by hhoechtl** [comment]
As soon as the official images are available for x64 https://hub.docker.com/_/php?tab=tags&page=1&ordering=last_updated&name=8.0-fpm

**Comment by Lukzat** [comment]
Hi, 8.0-fpm is already available on the docker hub, so when will it be? I'm already looking forward to trying PHP 8.  :D
Thank you!

**Comment by hhoechtl** [comment]
It is since a few days. You should join our Slack channel. Announcements are posted there.
