### ISSUE TITLE
Update PHP (official) to 7.4.13 to fix preloading bug

### ISSUE THREAD

**Issue by Swahjak** [webdevops/Dockerfile#381]
First of all: Great repository, many thanks! Absolute life saver.

The reason for my request https://github.com/symfony/symfony/issues/39010#issuecomment-736762938. PHP 7.4.12 causes issues when using preloading (with Symfony). This issue seems to be resolved in PHP 7.4.13.

**Comment by hhoechtl** [comment]
Thanks for your interest @Swahjak . Our images are updated every night (if the build succeeds and no downtime on github or any other dependent package source occurs).

Therefore:
```
docker run --rm -ti webdevops/php:7.4 php -v
PHP 7.4.13 (cli) (built: Dec  1 2020 04:25:48) ( NTS )
Copyright (c) The PHP Group
```

**Comment by Swahjak** [comment]
I would swear on my mother that yesterday docker hub showed a different status, but anyways now it does show that the latest build was yesterday :+1: Once again; thanks for the effort!
