### ISSUE TITLE
Xdebug warnings

### ISSUE THREAD

**Issue by stadeleon** [webdevops/Dockerfile#385]
https://github.com/webdevops/Dockerfile/blob/d29fb103aa8e21450fd853faa698cb72edf263c1/docker/php-dev/8.0/conf/provision/bootstrap.d/20-php-module-xdebug.sh#L34

Xdebug: [Config] The setting 'xdebug.profiler_output_dir' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_output_dir (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_autostart' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)
Xdebug: [Config] The setting 'xdebug.remote_enable' has been renamed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable (See: https://xdebug.org/docs/errors#CFG-C-CHANGED)

**Comment by hhoechtl** [comment]
Duplicate of #384
