### ISSUE TITLE
webdevops/php-nginx for production site?

### ISSUE THREAD

**Issue by dnarsain** [webdevops/Dockerfile#398]
Hi,

I am not good at making my own Dockerfile so I am thinking to use this image for my Magento 2 production site project.

Is these images for developers only or can be used on production? i have security concerns.

Thanks...

**Comment by hhoechtl** [comment]
The images `webdevops/php-nginx` is for production purpose. The `webdevops/php-nginx-dev` is for development and should never be deployed to a production system.

If you are concerned about security, you should add your custom nginx configuration to the container/image. I recommend this talk: https://www.youtube.com/watch?v=VtKTOZFfoug to get some useful tipps.
