### ISSUE TITLE
Datadog tracing agent is breaking

### ISSUE THREAD

**Issue by rodosskiand** [webdevops/Dockerfile#405]
As I understand this issue affects using dd agent in php-nginx images: https://github.com/DataDog/dd-trace-php/issues/483
When I installed dd agent I get 502 error and SIGSEGV.

Possibly should make using ioncube optional? 

Image: webdevops/php-ngnx:7.4
environment: kubernetes 1.20.6 (managed by KOPS), ubuntu:20.04.02LTS, contained 1.4.4

Thanks!

**Comment by uttamkasundara** [comment]
Please check with the latest version: https://github.com/DataDog/dd-trace-php/releases/tag/0.71.0

**Comment by hhoechtl** [comment]
You can use the env variable `PHP_DISMOD=ioncube` to disable ioncube
