### ISSUE TITLE
[QUESTION] how to use a self signed certificate for 2 subdomains?

### ISSUE THREAD

**Issue by neoacevedo** [webdevops/Dockerfile#406]
Hi. 

I am using webdevops/php-apache for local development. I don't use the php-apache-dev because I don't need xdebug. I have made a self signed certificate for 2 subdomains (admin.mydomain.co & web.mydomain.co) in my openSUSE machine where I previously had the subdomains and these certificates worked, but now, in this docker, when I try to use the https I get the error SSL_ERROR_RX_RECORD_TOO_LONG

Then, my question is how to use my current certificates or at least, how to create a new one for my two subdomains?

**Comment by garbinmarcelo** [comment]
Were you able to use https? I'm also wondering how to use...

**Comment by neoacevedo** [comment]
0 and I think it wouldn't have any response so I will close this issue.
