### ISSUE TITLE
PHP gmp module

### ISSUE THREAD

**Issue by neoacevedo** [webdevops/Dockerfile#413]
How to install `gmp` module?

**Comment by hhoechtl** [comment]
We build most PHP modules ourselves during the build process as the vanilla `_/php` images don't include the modules and some take a serious amount of time.
Gmp was never required until now. You can add it yourself with:

```
FROM webdevops/php:7.4
apt-install libgmp-dev
docker-php-ext-install gmp
```

I will include it in the build pipeline soon.
