### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by neoacevedo** [webdevops/Dockerfile#414]
Is this project still active?

**Comment by hhoechtl** [comment]
Yes it is. I'm currently refactoring the build pipeline on gitlab runners.
Do you need anything in particular?

neoacevedo ***@***.***> schrieb am Mo., 26. Juli 2021, 19:54:

**Comment by neoacevedo** [comment]
Yes, for instance: https://github.com/webdevops/Dockerfile/issues/413

Also: https://github.com/webdevops/Dockerfile/issues/406 and https://github.com/webdevops/Dockerfile/issues/413

**Comment by hhoechtl** [comment]
#406 Is most likely something nobody has done yet. We all use the containers as http only and have a reverse proxy in front (dinghy/http-proxy) with certificates installed via mkcert.
