### ISSUE TITLE
Update Tag

### ISSUE THREAD

**Issue by nrhooks17** [webdevops/Dockerfile#416]
Will the webdevops/php-nginx image for PHP 7.4 be updated to the latest version of PHP 7.4? The image is currently at 7.4.19 and the latest version of php 7.4 is 7.4.22.

**Comment by hhoechtl** [comment]
The images are built every night and are based on `library/php:fpm`. Therefore as soon as the base images have the new version, we will have it one day later.
If you pull `webdevops/php-nginx:7.4` now, it's 7.4.22.

**Comment by nrhooks17** [comment]
Thanks!

**Comment by hhoechtl** [comment]
Oh there was an error in the build pipeline for `7.4-alpine`. I'm fixing it right now

**Comment by nrhooks17** [comment]
Thank you!
