### ISSUE TITLE
PHP 8.1 image

### ISSUE THREAD

**Issue by shyim** [webdevops/Dockerfile#420]
There is currently no PHP 8.1 image

**Comment by hhoechtl** [comment]
Well there's no PHP 8.1 ;-)

**Comment by shyim** [comment]
Would be nice to have one 😅 . So we can test Shopware in our CI :)

**Comment by hhoechtl** [comment]
OK, I'll prepare one this week

**Comment by shyim** [comment]
any news?

**Comment by hhoechtl** [comment]
There's still no official `php:8.1-fpm` image

**Comment by Ozerich** [comment]
The official php:8.1-fpm image appears
https://hub.docker.com/layers/php/library/php/8.1.0-fpm/images/sha256-61812c4489ab538dcd8771dac5a8a82ddb3a927c95072a57c1623ed154613a7f?context=explore

@hhoechtl make pls php8.1 image 

Thank you

**Comment by hhoechtl** [comment]
The first images have been pushed:
![image](https://user-images.githubusercontent.com/5076356/144065430-9818c38a-e9b5-46ef-972b-ac7f2ed8f368.png)

Unfortunately `xmlrpc` and `tokenizer` are not yet available/working. I'll have to adapt the tests accordingly. But you can already use the images.

**Comment by FedericoBiccheddu** [comment]
@hhoechtl thank you so much for your work and promptly image push 🙏

**Comment by coding46** [comment]
> Unfortunately `xmlrpc` and `tokenizer` are not yet available/working. I'll have to adapt the tests accordingly. But you can already use the images.

tokenizer ist already built-in. No need to add it here. :)
https://github.com/docker-library/php/issues/1231#issuecomment-982762459

**Comment by shyim** [comment]
Can you add the image to your CI so its regulary updated? I guess I have a problem with 8.1.0 vs 8.1.1

**Comment by hhoechtl** [comment]
It's added but building 8.1 in CI throws a SIGSEGV which I'm not able to reproduce and therefore to solve.
I'm building them locally atm.

**Comment by vebe** [comment]
Is the 8.1 image officially ready to use? I'm asking as it's missing in the documentation: https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html#docker-image-tags

**Comment by hhoechtl** [comment]
Yes it is. You know ... documentation comes last

**Comment by wouter-toppy** [comment]
is there any update on this?

still no 8.1 image without nginx 
https://github.com/webdevops/Dockerfile/tree/master/docker/php-official

**Comment by hhoechtl** [comment]
I'm working on a new CI process for quite a while. The current version is here: https://gitlab.com/webdevops/Dockerfile/-/tree/php-ci/docker/php-nginx

**Comment by RogerSik** [comment]
An 8.1 image exists now but since 22 days there where no rebuild on docker hub.

Example
* webdevops/php-apache
* webdevops/php-nginx

8.0 is uptodate. Is there a build problem with 8.1 images?

**Comment by hhoechtl** [comment]
@RogerSik thanks for notifying, I've fixed an issue with the gitlab runners.
