### ISSUE TITLE
FPM Status page?

### ISSUE THREAD

**Issue by Mugane** [webdevops/Dockerfile#444]
Can someone please provide instructions on how to get the PHP-FPM status page to show at the URL `/status` or similar for any of the nginx-php images? None of the instructions available for this that I've found work, primarily because they assume generic setup of nginx/php instead of whatever the webdevops image does. Uncommenting the `;pm.status_path = /status` line in any of the `/opt/docker/etc/php/fpm/pool.d/` config files and restarting nginx (or the image itself) does nothing. I'm assuming there's a location segment that needs to be added to `/opt/docker/etc/nginx/vhost.conf` but what is it? Here's a starting point to get a running image with the status_path uncommented (I don't know how to code a restart of php-fpm so I just restart the container):
```
docker run -d --name fpm-test -p 8088:80 webdevops/php-nginx:7.4
docker exec -it fpm-test /bin/bash -c "sed -i 's/;pm.status_path/pm.status_path/g' /opt/docker/etc/php/fpm/pool.d/*.conf*"
docker restart fpm-test
```
Try opening http://127.0.0.1:8088/status (results in File not found).

**Comment by hhoechtl** [comment]
We do it like this:

```Dockerfile
FROM webdevops/php-nginx:8.0
COPY --chown=1000:1000 docker/ /opt/docker/
```

We have `docker/bin/service.d/php-fpm.d/99-status.sh`:

```shell
`echo "pm.status_path = /_ah/status" >> /opt/docker/etc/php/fpm/pool.d/application.conf`
```

`docker/etc/nginx/vhost.common.d/10-healthcheck.conf`:

```
# This default behavior is intentionally using regex to allow
# users to override this with the exact match directive as follows:
# location = /_ah/health {
#   # Define your own behavior.
# }
#
location ~ ^/_ah/health$ {
   access_log off;
   return 200 'ok';
}

location ~ ^/_ah/status$ {
  access_log off;
  #allow 127.0.0.1;
  #allow 1.2.3.4#your-ip;
  #deny all;
  include fastcgi_params;
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  fastcgi_pass php;
}
```

**Comment by Mugane** [comment]
Thanks @hhoechtl - perfect solution - It works for me now with the following location code in `/opt/docker/etc/nginx/vhost.conf
` (this may be different for >7.4 or there may be several places where you can put this, but it's basically wherever the nginx config is, within the `server { ... }` section): 
```
    location /status {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php;
    }
```
