### ISSUE TITLE
PHP 8.2 Image

### ISSUE THREAD

**Issue by shyim** [webdevops/Dockerfile#452]
Similar too https://github.com/webdevops/Dockerfile/issues/420

**Comment by alextesi** [comment]
I need this too

**Comment by hhoechtl** [comment]
Now available:

```
webdevops/php:8.2
webdevops/php-apache:8.2
webdevops/php-nginx:8.2
```

The `-dev` and `php-alpine` images don't work yet due to xdebug and some weird library issues on alpine. Will fix them asap.
