### ISSUE TITLE
PHP security releases: 8.1.16, 8.2.3, 8.0.28

### ISSUE THREAD

**Issue by bramcordie** [webdevops/Dockerfile#477]
February 14th 2023 there were security releases for the 3 currently supported PHP versions:
- [PHP 8.2.3](https://www.php.net/archive/2023.php#2023-02-14-2)
- [PHP 8.1.16](https://www.php.net/archive/2023.php#2023-02-14-3)
- [PHP 8.0.28](https://www.php.net/archive/2023.php#2023-02-14-1)

I'm using [webdevops/php-apache:8.1-alpine](https://hub.docker.com/layers/webdevops/php-apache/8.1-alpine/images/sha256-bae16e5828b0312b0ff040d36e22a151e99db802f64a20d2073cc11c05e8aca8?context=explore) specifically, which seems to be behind on 8.1.14.

What's the process for getting these PHP security releases upgraded in all relevant images? Is there anything I can do to help, besides mentioning new versions here?

**Comment by hhoechtl** [comment]
The builds are automatically executed at https://gitlab.com/webdevops/Dockerfile/-/pipelines 
But there's been a breaking change in docker (buildkit is deprecated and enabled by default), which broke the building process.
I just fixed it and the images are being built
