### ISSUE TITLE
Question about ongoing hosting of webdevops docker images

### ISSUE THREAD

**Issue by tractorcow** [webdevops/Dockerfile#478]
Apparently docker's policy on free / open source images has changed. https://blog.alexellis.io/docker-is-deleting-open-source-images/

Can the team confirm if they will be affected by this change, and if so, if there is anything we should be doing (as image users) prior to this change? Thanks :)

**Comment by hhoechtl** [comment]
I'm not sure who of us received that mail. But as we're building all images on gitlab since a while, we have a copy at e.g. https://registry.gitlab.com/webdevops/dockerfile/php-apache:8.2

You can check out the builds at https://gitlab.com/webdevops/Dockerfile
