### ISSUE TITLE
webdevops/php-nginx:7.4 and webdevops/php-apache:7.4

### ISSUE THREAD

**Issue by alextesi** [webdevops/Dockerfile#480]
missing php-mysql driver

**Comment by hhoechtl** [comment]
Can not verify:

```
➜  ~ docker run --rm -ti webdevops/php-nginx:7.4 php -m | grep mysql
mysqli
mysqlnd
pdo_mysql
```

**Comment by alextesi** [comment]
repulled the last version and I executed your command:
[/]: php -m | grep mysql
mysqlnd

**Comment by hhoechtl** [comment]
You're executing the exact same command? You don't have any volume mounts, environment variables or something else present?
The hash of the latest image (today) is `sha256:41bbfdd2e627d926ed9571e1e653b1c4936ad20b7f667a06d2c2619a072d0cb7`
