### ISSUE TITLE
Something weird is happening on webdevops/php-nginx repository

### ISSUE THREAD

**Issue by legolabs** [webdevops/Dockerfile#486]
I'm using webdevops/php-nginx:8.1-alpine as a base. Today I had an error, never had before, "Class Imagick not found".
I checked on dockerhub, and that's something strange: all releases are updated 9 hours ago, but nothing on this github project was modified. 

What's happening?

**Comment by refactor73** [comment]
same here:

`PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so (Error loading shared library libgomp.so.1: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20210902/imagick.so.so: No such file or directory)) in Unknown on line 0
`

webdevops/php-nginx-dev:8.1-alpine

**Comment by tobias-trozowski** [comment]
can confirm this too.

i got it "fixed" with a custom `Dockerfile`:
```Dockerfile
FROM webdevops/php-nginx-dev:8.1-alpine

RUN apk add --update --no-cache libgomp
```

**Comment by hhoechtl** [comment]
Even if the images are not altered they're rebuilt every night to have current minor updates in place: https://gitlab.com/webdevops/Dockerfile/-/pipelines

Could be possible that alpine has changed something in their packages.

Fix is committed and pipeline is running: https://gitlab.com/webdevops/Dockerfile/-/pipelines/866828058
