### ISSUE TITLE
ICU update changed something on locale

### ISSUE THREAD

**Issue by jaakkom** [webdevops/Dockerfile#488]
After update of icu 66 > 73, we are experiencing changed results on unit tests. Is this wanted behavior or not?

Example:

```
--- Expected
+++ Actual
@@ @@
-'Pekka Stubb, 2/29/16, 12:00:00 AM'
+'Pekka Stubb, 2/29/16, 00:00:00'
FmtLogTest.php:33
3) ItemizationTest::testFmtLogs with data set #0 ('<strong>&lt;Pekka Stubb, 2/29...r><br>', 'en_UK', 'Europe/Stockholm', array(array('Keskeytetty', '2016-02-28 23:00:00')))
```

https://github.com/webdevops/Dockerfile/commit/117c017b83fcd0de8c5c3e3d4fc7e6ec2863dc3c

**Comment by hhoechtl** [comment]
We did just update the ICU library. 
As PHP Intl is a wrapper for the ICU library, it's possible that some things might change if you use Calender, Normalizer, etc.

That is intended behavior as the ICU library keeps advancing and they're fixing things too.
