### ISSUE TITLE
Invalid Discord invitation-link

### ISSUE THREAD

**Issue by snowowl78** [webdevops/Dockerfile#490]
Trying to get in contact  via discord I found the publicized discord-link.
> Or join our discord https://discord.gg/gnYPfZhX

By clicking to follow the invitation discord prompts that this link is invalid

Any chance to get a valid invitation link?

**Comment by mblaschke** [comment]
please retry

**Comment by snowowl78** [comment]
The behaviour is unfortunatly unchanged

![grafik](https://github.com/webdevops/Dockerfile/assets/17596877/32adfa74-b82f-47aa-9c10-47209d25ff5c)

**Comment by hhoechtl** [comment]
Try https://discord.gg/9uqKaHVXQP

**Comment by mblaschke** [comment]
please use https://discord.gg/BpBZtXAgJz
