### ISSUE TITLE
webdevops/php-nginx-dev:8.3-alpine contains wrong PHP Version

### ISSUE THREAD

**Issue by prodigy7** [webdevops/Dockerfile#508]
I try to build a own image based on webdevops/php-nginx-dev:8.3-alpine and recognized, that this image contains php in version 8.2.

`PHP 8.2.14 (cli) (built: Dec 27 2023 23:59:27) (NTS)`

It seems, webdevops/php-nginx:8.3-alpine is okay and has the right php version.

**Comment by prodigy7** [comment]
Related line: https://github.com/webdevops/Dockerfile/blob/master/docker/php-nginx-dev/8.3-alpine/Dockerfile#L6

**Comment by htuscher** [comment]
Solved in https://github.com/webdevops/Dockerfile/commit/4f8fc7eade862d731446c1c8c0bb86e7df995ed0
