### ISSUE TITLE
Missing libldap-common package in PHP 8.3 Docker image causing ldaps connections to fail

### ISSUE THREAD

**Issue by LemmingZwerg1** [webdevops/Dockerfile#509]
# Description
I have recently upgraded the PHP Docker image I'm using from webdevops/php-apache-dev:8.2 to webdevops/php-apache-dev:8.3 and encountered an issue where I could not establish an ldaps connection from my PHP application.

I've narrowed down the cause to the libldap-common package being absent in the PHP 8.3 image. After manually installing libldap-common, the ldaps connections worked fine as before. I believe this package was present in the PHP 8.2 Docker image and appears to have been removed or is missing in the PHP 8.3 image.

# Steps to Reproduce:
- Use PHP 8.3 Docker image (webdevops/php-apache-dev:8.3) in your environment
- Attempt to establish an ldaps connection from a PHP application
- Observe that the connection fails
- Install libldap-common package in the image
- Attempt to establish the ldaps connection again

# Expected Result:
The application should be able to establish ldaps connections without needing to manually install additional packages.

# Actual Result:
The application is unable to establish an ldaps connection until libldap-common is manually installed.

# Proposed Solution:
Please include the libldap-common package in the PHP 8.3 Docker image or ensure the LDAP module is properly configured to allow ldaps connections out of the box.

Best regards, Tobias

**Comment by thierrydrc** [comment]
Same issue...
Waiting for fix 🙏

**Comment by LemmingZwerg1** [comment]
@htuscher  thx!
