### ISSUE TITLE
Add ioncube loader

### ISSUE THREAD

**Issue by hhoechtl** [webdevops/Dockerfile#52]
It would be nice if there would be a flag/switch to install and enable ioncube loader.
It's currently not available for PHP7 but for the other PHP versions. 
This way it would be possible to have a boilerplate for Shopware or other PHP applications that use ioncube.

**Comment by simonschaufi** [comment]
yes, that would be great!

**Comment by hhoechtl** [comment]
I built an install script but it's currently only tested with Ubuntu 16.04: https://github.com/1drop/shopware52-docker/blob/develop/etc/php/ioncube.sh
