### ISSUE TITLE
Is there a way to still use the buster when I use the webdevops/php-nginx:8.1?

### ISSUE THREAD

**Issue by cocolees** [webdevops/Dockerfile#520]
Hi, I saw the latest update the php base images to upgrade from buster to bookworm, is there a way to still use the buster when I use the webdevops/php-nginx:8.1?

Our server Linux version is old and will occur unexpected errors when use the webdevops/php-nginx:8.1 which base image is bookworm

**Comment by htuscher** [comment]
The beauty of docker is that you mustn't care about the host system. There should be no difference.

If you want to continue the old image, you must pin your digest version.

**Comment by cocolees** [comment]
Ok, Thanks
