### ISSUE TITLE
Any way to define custom `php.ini` ?

### ISSUE THREAD

**Issue by FezVrasta** [webdevops/Dockerfile#53]
I'd like to add a custom php ini to the php-nginx environment, but if I mount `/etc/php5/fpm/conf.d/` from host then I'll lose all the configurations provided by the image.

How can I proceed?

**Comment by mblaschke** [comment]
You can use `/opt/docker/etc/php/php.ini` for this.

**Comment by FezVrasta** [comment]
Thanks but how am I supposed to edit the content inside it?

I should mount the `/opt/docker/etc/php/` directory, but this would overwrite everything in that folder...

**Comment by mblaschke** [comment]
In your Dockerfile you can use:

`ADD your-php.ini /opt/docker/etc/php/php.ini`

**Comment by FezVrasta** [comment]
Thanks!
