### ISSUE TITLE
Referring to environment variable within PHP

### ISSUE THREAD

**Issue by r24y** [webdevops/Dockerfile#54]
I'm using `webdevops/php-apache:debian-8`, and I wish to pass configuration parameters to the app via environment variables (accessible via getenv()). However, when I display `phpinfo()`, the only two environment variables are `USER` and `HOME`. Somewhere in `init process > supervisord > apache > php` the environment variables aren't getting handed down. I've been researching for hours and would really love a nudge in the right direction.

Of course I don't expect anything for free, would love to give back in terms of code or documentation, just stuck in a tight spot right now :)

**Comment by mblaschke** [comment]
PHP-FPM is clearing all ENV-vars by default (because of security issues). You have to add all ENV-vars to the pool configuration:

http://php.net/manual/en/install.fpm.configuration.php#example-74


or use our [PHP Docker Boilerplate](https://github.com/webdevops/php-docker-boilerplate).

For the future: we're planing a yml configuration for advanced provisioning which also sets the env-vars for FPM.

**Comment by r24y** [comment]
Thanks a million! :tada: this really helps me a ton. @mblaschke I'll leave it up to you whether to close this issue since I know sometimes project maintainers like to leave these things open. My problem is solved though.

In case anyone else comes across this thread looking for a quick resolution: I started my container as usual, then ran: 
```
mkdir fpm-conf
docker exec my_container cat /etc/php5/fpm/pool.d/application.conf > fpm-conf/application.conf
```

Then in my Dockerfile, added the line
```
COPY ./fpm-conf/application.conf /etc/php5/fpm/pool.d/application.conf
```

Works like a charm and I can now pass environment variables to my PHP!

**Comment by Snaver** [comment]
This is a bit easier now (if you don't mind comprising security on a local machine?..).

**Dockerfile**

> ENV APPLICATION_ENV=development
> 
> ENV fpm.pool.clear_env=false

See here for documentation https://secure.php.net/manual/en/install.fpm.configuration.php#clear-env.
