### ISSUE TITLE
Debian8 PHP7 Dotdeb SIGABRT

### ISSUE THREAD

**Issue by hhoechtl** [webdevops/Dockerfile#56]
When using TYPO3 with debian8 and php7 I'm experiencing the same issues as I reported here:
https://github.com/gplessis/dotdeb-php/issues/124

**Comment by hhoechtl** [comment]
@mblaschke how about switching from dotdeb to something else, e.g. https://deb.sury.org/
Didn't test it yet, but looks promising.

**Comment by trendzetter** [comment]
@hhoechtl https://github.com/gplessis/dotdeb-php/issues/124#issuecomment-211075080

**Comment by trendzetter** [comment]
@hhoechtl I am considering trying unstable packages from sid before trying compilation. Did you consider the sid packages? It seems like a suitable solution for a docker.

**Comment by trendzetter** [comment]
I am trying to use debian "testing" packages but I have unmet dependencies:
```
The following packages have unmet dependencies:
 php7.0-readline : Depends: libtinfo5 (>= 6) but 5.9+20140913-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by trendzetter** [comment]
When unpinning testing the install works but the issue remains   :(

**Comment by mblaschke** [comment]
We're preparing ubuntu 16.04 with default php7 so it will be a alternative for dotdeb image.

**Comment by trendzetter** [comment]
@mblaschke It could be this patch is needed:
https://github.com/php/php-src/commit/92233dd736a883c34d5769081a9c0ff6d9f264f7

**Comment by mblaschke** [comment]
@trendzetter But it's still an upstream issue, dotdeb or php.net should fix it

PS: ubuntu 16.04 AND debian-9 will be php7 only
