### ISSUE TITLE
How to modify /opt/docker/etc/nginx/vhost.conf on-the-fly?

### ISSUE THREAD

**Issue by 18601673727** [webdevops/Dockerfile#57]
Hi, I'm excited to find your nice work which named `webdevops/php-nginx`, this image gives me lots of convince of deploying things but I have to add some parameters in `location ~ \.php$ {}` block before bootstrapping the app, any suggestions?

Thank you!

**Comment by mblaschke** [comment]
You can "upload" a custom configuration and overwrite the stored configuration inside the container with `ADD` or `COPY` inside your `Dockerfile`.

There will be a configuration for setup but it needs more time.

**Comment by 18601673727** [comment]
@mblaschke I did what u told me to but if I did it right https://gist.github.com/18601673727/0ea43adde6691af201552b42285add7e

**Comment by mblaschke** [comment]
Hint: The new images will provide a modular design

**Comment by mblaschke** [comment]
New images are available, just `ADD` your custom stuff into `/opt/docker/etc/nginx/vhost.common.d/`

http://dockerfile.readthedocs.io/en/latest/content/DockerfilesUsage/dockerfiles/nginx.html

**Comment by 18601673727** [comment]
Great!!

**Comment by 18601673727** [comment]
Great!!
