### ISSUE TITLE
Alpine PHP not working

### ISSUE THREAD

**Issue by hhoechtl** [webdevops/Dockerfile#70]
When the playbooks are running in either php-nginx:alpine-3, php-nginx:alphine-3-php7 or php-apache:alpine-3 and php-apache:alpine-3-php7 ansible can't finish because of these two errors:

    TASK [boilerplate-main : Create link for crontab] ******************************
    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error while linking: [Errno 2] No such file or directory", "path": "/etc/cron.d/docker-boilerplate", "state": "absent"}
	to retry, use: --limit @/opt/docker/provision/playbook.retry

After I fixed that by commenting out crontab, this one appeared:

    TASK [boilerplate-main : Configure aliases] ************************************
    failed: [localhost] (item={u'destination': u'root@example.com', u'user': u'root'}) => {"failed": true, "item": {"destination": "root@example.com", "user": "root"}, "msg": "Destination /etc/aliases does not exist !", "rc": 257}
	to retry, use: --limit @/opt/docker/provision/playbook.retry

**Comment by mblaschke** [comment]
Thanks for reporting but please give us some time while refactoring our Dockerfiles.
We want to replace the provisioning of the boilerplate and move it inside the Docker images which makes updating easier.

**Comment by mblaschke** [comment]
Fixed with 0.51.0
da823c0239a49e4664fa44a05b18052ee4c02669
