### ISSUE TITLE
can't access container from web browser for php 5.3 

### ISSUE THREAD

**Issue by puterakahfi** [webdevops/Dockerfile#71]
hi all, 
I have created a container for php 5.3 
here the command :
docker run -d  -p 8082:80 --name php53  --link mariadb:mariadb -e WEB_DOCUMENT_ROOT=/media/WEBSITE  webdevops/php-apache:ubuntu-12.04

but when I access in browser with localhost:8082
I got 
This site can’t be reached

is there something wrong my command ?

thanks 
kahfi

**Comment by mblaschke** [comment]
can you post your docker logs from this container?

PS: don't forget to mount your /media/WEBSITE inside your container :)

**Comment by mblaschke** [comment]
Closing because of no reaction for more than one month.
