### ISSUE TITLE
php-dev on docker hub

### ISSUE THREAD

**Issue by julianxhokaxhiu** [webdevops/Dockerfile#73]
Are you going to push these images on Docker hub? And if so, when?

Thanks in advance!

**Comment by mblaschke** [comment]
yes we will push these images when the refactoring is finished.
We have still some smaller tasks to do so give us some time :)

PS: want to you slack? :)

**Comment by julianxhokaxhiu** [comment]
Oh thank you! I hope it will be soon :)

Sure! Which is the URL? I didn't knew you had Slack

**Comment by mblaschke** [comment]
Feel free to use our invitation service :)
https://webdevops.io/slack

**Comment by mblaschke** [comment]
I've added the repos for php-*dev but it still needs some time to get the stuff finished.

**Comment by julianxhokaxhiu** [comment]
Super awesome! Thank you, I'll try them asap :)

I'll close this issue since now it's fixed.
